### ISSUE TITLE
Default Docker Image in ARM template is missing a tag

### ISSUE THREAD

**Issue by jjcollinge** [opencb/opencga#1010]
The current default Docker Image for the init container in the ARM template is incorrect (does not exist). We need to sort out what official OpenCGA images are and where they're stored. Then we can update the defaults in the template. For now please override with the values from the conversation in #969.

https://github.com/opencb/opencga/blob/f5fd34d9a88a5a4ccff5835f631076df9a200e02/opencga-app/app/scripts/azure/arm/azuredeploy.json#L177

**Comment by jjcollinge** [comment]
Default values removed until official images available

**Comment by marrobi** [comment]
Is this the same as #1060 ?

Feel we should get this in so the templates deploy as is.

**Comment by jjcollinge** [comment]
Closing as will apply fix for #1060
