### ISSUE TITLE
Healthcheck endpoint in OpenCGA

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#1015]
Having a healthcheck as an endpoint would be very useful and it would make things easier. After some thoughts it seems a good idea to make this new _status_ private, so we propose to implement this in the endpoint:

    _admin/status_

Note: we will keep (and improve) current **meta/status** with very basic information such as https://www.githubstatus.com/, for instance: {catalog: OK, storage: warning, ...}

**New admin/status Endpoint**
This new healtchcheck endpoint will provide detailed information about the whole cluster installation. We are thinking of something like this:

    version: 1.4.0,
    commit: "",
    installationDir: "",
    javaVersion: "",

    catalog: {
        installation: {
            installed: false,           // installation CLI executed succesfully
            incidents: [
                "conf/configuration.yml not found"
            ]
        },

        database: {
            name: "MongoDB 3.6.6",
            driver: "mongodb-java-driver-3.6.4",
            running: true,              // MongoDB is running
            writable: false,            // OpenCGA can connect and write into Catalog
            incidents: [
                "MongoDB driver is 3.6.4", 
                "We cannot write into database"
            ]
        },

        sessions: {
            path: "/A/B/C",
            readable: true,
            writable: true
        },

        search: {
            ...
        }
    },

    storage: {
        ...
    },

    server: {
        name: "Tomcat 8.0.53",
        running: true,
        accessToInstallationDir: true   // checks if it can read configuration files
        accessToSessions: true,         // checks if OpenCGA can read and write in the 'sessions' folder
    },

**Comment by wbari** [comment]
AZ requirements :

1: Single status WS
2: 500 error code in case of failure

**Comment by wbari** [comment]
#1136

**Comment by wbari** [comment]
merged code changes for AZ. Existing meta/status WS will return status of CatalogMongoDB, StorageDb (MongoDB or HBase , based on storageEngineId in configuration) and Solr ( optionally can be deactivated from configuration ) and in case of error return status code 500.

**Comment by lawrencegripper** [comment]
Awesome, looking forward to giving this a test next week!

**Comment by marrobi** [comment]
@wbari solr seems to be good now, but getting:

```
{"apiVersion":"v1","time":-1,"warning":"","error":"No storageEngineId is set in configuration","queryOptions":{"metadata":true,"skipCount":true,"limit":2000},"response":[{"id":"Status","dbTime":0,"numResults":-1,"numTotalResults":-1,"warningMsg":"Future errors will ONLY be shown in the QueryResponse
body","errorMsg":"DEPRECATED: No storageEngineId is set in configuration","resultType":"","result":[]}]}
```

**Comment by marrobi** [comment]
```{"apiVersion":"v1","time":885,"warning":"","error":"","queryOptions":{"metadata":true,"skipCount":true,"limit":2000},"response":[{"id":"Status","dbTime":0,"numResults":-1,"numTotalResults":-1,"warningMsg":"","errorMsg":"","resultType":"","result":[{"VariantStorage hadoop":"OK","Solr":"OK","CatalogMongoDB":"OK"}]}]}``` 👍

**Comment by martinpeck** [comment]
Actions:
- [ ] move config set to github (currently in Confluence)
- [ ] allow configurable time interval
- [ ] allow/consider caching the health check response

**Comment by martinpeck** [comment]
related to PR #1150

**Comment by wbari** [comment]
created tasks for each items ( except last one which lawrencegripper mentioned already handled in TF

**Comment by lawrencegripper** [comment]
I agree this is good to close off now
