### ISSUE TITLE
Proposal for ARM improvements

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#1018]
This is an issue to look at some of the problems we've had with ARM and what we can look to do to help improve the situation.

**Comment by lawrencegripper** [comment]
# Problem Statement  - What's wrong and what can we fix?

The current work on using ARM to deploy [OpenCGA is available on the Azure Branch](https://github.com/opencb/opencga/tree/azure/opencga-app/app/scripts/azure/arm). The information below is based on the work to date. 

To illustrate the issues seen I'll provide a little detail what is being deployed. Firstly the system can be configured in three different sizes #1040. Each different deployment size will conditionally turn on resources, change VM Sizes or more from HA systems to single node systems. 

The solution consists of:

- HDInsights HBase Cluster
- Avere VFXT filesystem
- AzureFiles SMB Share
- Solr Cluster /w Zookeeper Cluster
- WebFarm running Tomcat, Apache and GRPC services
- Backend Daemon VM
- Azure Batch pool for Job processing 
- MongoDB Replicaset Cluster
- Application Gateway for Layer7 routing
- Multi-Subnet configuration with network rules
- One-click deploy so Java application is initialized with outputs from all clusters to provide working system

**Comment by lawrencegripper** [comment]
## Problem 2: Multi-line inputs (`CloudInit` and `scripts`)

When initializing machines we use [`cloud init inline`](https://github.com/opencb/opencga/blob/08f9383409f183624c5c0f2627ac52e9b361fb30/opencga-app/app/scripts/azure/arm/webservers/azuredeploy.json#L112), [`cloud init encoded`](https://github.com/opencb/opencga/blob/08f9383409f183624c5c0f2627ac52e9b361fb30/opencga-app/app/scripts/azure/arm/mongodb/azuredeploy.json#L175) and `scripts`. These all tend to extend beyond simple, short, one line entries.

**Comment by lawrencegripper** [comment]
## Development Tooling: Schema Validation

We have written a [CLI tool](https://github.com/lawrencegripper/armvalidationcli) to give us build-time validation in our CI builds when editing the templates. 

However, what we witness is that LOTS of the schemas are out of date or incorrect. [Our ignore file is pretty huge at this point](https://github.com/opencb/opencga/blob/08f9383409f183624c5c0f2627ac52e9b361fb30/opencga-app/app/scripts/azure/arm/armvalconfig.json) and this means the CLI validation is of questionable value. 

Here is an example, [it is flagged as a schema failure but is valid to the service](https://github.com/opencb/opencga/blob/cabd27f/opencga-app/app/scripts/azure/arm/webservers/azuredeploy.json#L296):  `Value is not accepted. Valid values: "Automatic", "Manual"`. This same issue occurs three times in the file for different incorrect schema values.

**Comment by lawrencegripper** [comment]
## Problem 4: Deployment times when no changes present

When working on such a large deployment all of us are frequently running the end-2-end deployment to test changes in a small area of the template. What we observe is that existing non-changed areas of the template take a long time to return recognizing that no changes are required. 

@marrobi, need to collect a bit of data to demonstrate this issue.

**Comment by lawrencegripper** [comment]
## Problem 5: Lack of simple code execution 

Many data-plane operations in services aren't supported by their ARM APIs. Such as [creating Azure files]('https://github.com/Azure/azure-quickstart-templates/issues/1444') this means workarounds are required. Luckily with Azure Container Instances and Managed Identity a lot of stuff can be made to work but this approach adds complexity. 

However, ACI returns after having been create NOT when the container has completed it's execution. This leads to race conditions on deployment when, depending on what gets done first, deployments fail as an expected Azure File exists or doesn't exist. 

We've [worked around this by adding retries to our scripts]('https://github.com/opencb/opencga/blob/08f9383409f183624c5c0f2627ac52e9b361fb30/opencga-app/app/scripts/azure/arm/avere/mount.py#L151') which attempt 100 times to mount the share with an exponential wait between each attempt. 

## Solution/Feedback

It would be great to create a server side script execution RP using ACI behind the scenes. This should allow the user to run a script as the ARM deployment identity (specifying a docker image to run from 'python'… etc) and then wait for it to execute, so any 'depends on' resource are blocked. Once it has executed output should be collected, either as JSON from stdout or environment variables or a file on disk. These outputs should be accessible to other resources as inputs as you can access a property on the existing RPs. See discussion here: https://twitter.com/dotjson/status/1074220570974261248

**Comment by avodovnik** [comment]
With _Problem 1_, the ability to "compile" the templates into a single one would also be really useful as we could then load the template into Armviz, which currently does not support linked templates.

**Comment by stuartleeks** [comment]
For Problem 1 (friction around needing templates public to deploy), I've tended to use Azure Storage for this when I'm in my dev cycle. This avoids having to commit and push changes just to test them, and also avoids the issue with caching that GitHub does on the raw content URLs.

I've normally just used a script file that uploads all the templates to Blob Storage and run that before running the deployment command. It could be worth exploring an Azure CLI extension to streamline this flow:

**Comment by tomconte** [comment]
For problem 2, there is this trick that is used by the A[CK]S-engine ARM template: https://blogs.technet.microsoft.com/jessicadeen/microsoft/azure-arm-templates-how-to-embed-full-scripts-in-your-json-templates/. Basically keep scripts separate and have a build task that gzip/base64 them and injects them into the template.

**Comment by marrobi** [comment]
I like @stuartleeks idea, perhaps could reuse cloud shell storage if available. If you could view artifacts via the portal for previous deployments, including scripts etc, that might be a nice feature.

**Comment by marrobi** [comment]
@tomconte  I tend to shy away from encodign scripts, as like the template content to be readable so you know what are deploying/have deployed. Downloading a template with an encoded script and just running it shouldn't be recommended, but many would do it.

**Comment by lawrencegripper** [comment]
@marrobi regarding the embedded scripts an option would be to have the code which doe it be reversible. I think it would be possible to give it a script and have decode and recreate the files on disk. 

The alternate, of having the script run a script from a URL feels even worse IMO... you can look at it before you deploy but it can be anything when the deployment runs as it can be changed. At least with the encoding you know exactly what the content is at deployment time.

**Comment by tomconte** [comment]
@marrobi for ARM deployments in general and Marketplace in particular, predictability of deployment is usually desirable, so it's actually good to embed external resources in order to eliminate external dependencies. In the specific case of the Marketplace though, since all dependencies end up being zipped together, you can keep external dependencies without risks. Many Marketplace solutions have been broken at one time or another because an external script or template was modified :) And keeping all dependencies going to a stable Github URL is pretty cumbersome...

**Comment by marrobi** [comment]
@tomconte agree 100%, the template should be deployable, as is, without external dependencies. It would be nice if we could do this with readable scripts.

**Comment by lawrencegripper** [comment]
We're currently experimenting with moving to TF as an alternative
