### ISSUE TITLE
Setup reverse proxy for routing - Application Gateway

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1023]
As discussed we'll go with Application Gateway Standard WAF first and test. 

Disable in `Small` deployments

**Comment by marrobi** [comment]
For App gateway v2, only option of Standard_v2 or WAF_v2, but is capacity configuration that is fixed or autoscale.

**Comment by marrobi** [comment]
Can have from 2 to 200 instances. Not available in UK datacenters.

**Comment by lawrencegripper** [comment]
An additional consideration which @j-coll raised yesterday is around the handling of the GRPC service. I believe that if we support HTTP2 routing then GRPC should work as expected but this is something that we'd need to review and test.

**Comment by marrobi** [comment]
Adding note as had to change VMSS update policy, as cannot see how to add health probes to VMSS when using App Gateway. Will investigate.

**Comment by martinpeck** [comment]
@wbari @j-coll @imedina to get the NGINX set up so that Marcus can expose the same/similar endpoints

**Comment by jjcollinge** [comment]
> An additional consideration which @j-coll raised yesterday is around the handling of the GRPC service. I believe that if we support HTTP2 routing then GRPC should work as expected but this is something that we'd need to review and test.

"HTTP/2 protocol support is available to clients connecting to application gateway listeners only. The communication to backend server pools is over HTTP/1.1." i.e. HTTP/2 from client to gateway but HTTP/1.1 to backend servers. Not sure how that'd play with GRPC. https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-faq#how-does-application-gateway-support-http2

**Comment by lawrencegripper** [comment]
Good spot, I think that's going to kill GRPC as IIRC the app is using it to stream over a persistent connection -  @imedina I am right in thinking GRPC is used for a persistent connection streaming data?

**Comment by marrobi** [comment]
Re rolling upgrades:

> VMSS Rolling upgrade requires some form of health monitoring (to validate the maxUnhealthy % that you’re setting). AppGW probes do not work in this case. You have two available options:
> 1.	Use custom LB probes – These are VM external probes. More on that https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-custom-probe-overview. 
> 2.	Use App Health extension – This is an in-guest approach for health. More on that https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension.

So we ahve a choice as to which we use. If we need a NLB tghen 1 makes sense, otherwise maybe 2. However what should we be probing as both IVA and opencga reside on the same VMSS.

**Comment by marrobi** [comment]
I've also asked product team if they have any info re HTTP2 to backends and GRPC.

**Comment by marrobi** [comment]
"This wouldn’t work till we support http/2 to the backend and protobuf. This is on the roadmap with no ETA yet."

**Comment by marrobi** [comment]
All LB probes must be used by a rule. So HTTP probes must a have a rule. All front end configs must be public or private. Believe this means if want to use http probes, not exposed they will need to be private LB. But if want GRPC (and SSH for testing), on a public will need a second Load blancer...!
