### ISSUE TITLE
Create Mechanism for applying T-Shirt Sizes to ARM Deployments

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1028]
We want to support Small, Medium and Large configurations for testing. Need to implement a way to allow the size of a deployment to be selected.

**Comment by martinpeck** [comment]
Need to update node sizes based on the conversation/whiteboard notes from today's discussion.

**Comment by lawrencegripper** [comment]
## Proposal

I've taken a quick look at this and wanted to put my thoughts down on the issue so we can see if this approach meets what others are expecting/thinking. This is a first draft and there are likely better ways to tackle it but I wanted to get the ball rolling. 

Within the template `parameters` we would define and integer based field for `deploymentSize` the description would outline the characteristics of each available size. 

```json
        "deploymentSize": {
            "type": "int",
            "allowedValues": [
                0, 1, 2
            ],
            "defaultValue": 0,
            "metadata": {
                "description": "What size of deployment do you want? 0 = For single researches testing things out. 1 = For x genomics with xgb per sec load rate. 2 = is for x/y"
            }
        },
```

I've gone with `int` as it makes the ARM easier to write and avoids the nasty trend of `extraLarge`, `mega`, `superMega`. In my example the description gives a quick overview on what each option offers. 

Next in the `variables` section of the template we use an array of identical config objects. Each of these represents the configuration of the solution at that size. Then the index is used the pull out the variables and build up the configuration which is later used in the template below. I've deliberately kept the scope of these changes to the `variables` section to keep alteration in the future easier. For example, if we moved away from the approach the `variables` section could be reworked but the `resources` section would remain the same. 

```json
        "sizingOptions": [
            {
                "type": "0 = Small",
                "avereEnabled": false,
                "azureFilesEnabled": true
            },
            {
                "type": "1 = Medium",
                "avereEnabled": false,
                "azureFilesEnabled": true
            },
            {
                "type": "2 = Large",
                "avereEnabled": false,
                "azureFilesEnabled": true
            }
        ],
        "selectedSize": "[variables('sizingOptions')[parameters('deploymentSize')]]",
        "avereEnabled": "[variables('selectedSize').avereEnabled]",
        "azureFilesEnabled": "[variables('selectedSize').azureFilesEnabled]"
```

Then later in the `resources` section the variables `avereEnabled` etc are used. 

```json
{
            "condition": "[variables('azureFilesEnabled')]",
            "resourceGroup": "[parameters('rgPrefix')]",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2018-05-01",
            "name": "azurefiles",
            "dependsOn": [
                "[parameters('rgPrefix')]"
            ],
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "[concat(parameters('_artifactsLocation'), '/azurefiles/azuredeploy.json', parameters('_artifactsLocationSasToken'))]",
                    "contentVersion": "1.0.0.0"
                }
            }
        },
```

**Comment by lawrencegripper** [comment]
Code testing this pushed here: https://github.com/lawrencegripper/opencga/blob/lg/issue/1028/opencga-app/app/scripts/azure/arm/azuredeploy.json#L193

**Comment by lawrencegripper** [comment]
Yeah that was my plan but looking at this now I'm not sure it makes sense duplicating all the properties. We could just reference the `selected-size` variable directly in the template and it would reduce the boiler plate code. 

```json
{
            "condition": "[variables('selectedSize').azureFilesEnabled]",
            "resourceGroup": "[parameters('rgPrefix')]",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2018-05-01",
            "name": "azurefiles",
            "dependsOn": [
                "[parameters('rgPrefix')]"
            ],
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "[concat(parameters('_artifactsLocation'), '/azurefiles/azuredeploy.json', parameters('_artifactsLocationSasToken'))]",
                    "contentVersion": "1.0.0.0"
                }
            }
        },
```

**Comment by martinpeck** [comment]
Agreed. Plus, when you're in the template, it's much easier to see that this is a variable that changed based upon t-shirt size.

**Comment by lawrencegripper** [comment]
Any objections to me starting to work on this then? Looks like #1040 is pretty much ready.

**Comment by marrobi** [comment]
Reckon can go for it.

**Comment by martinpeck** [comment]
Blocked on #1024 as we want to get that done first

**Comment by lawrencegripper** [comment]
As #1024 is now resolved moving to start working on this issue now.

**Comment by lawrencegripper** [comment]
Limitations of the current PR #1050 

- Currently the `solr` template doesn't support increasing the `nodeCount` property. It only supports 1 or 2 nodes. 
- Avere nodes can have either 1TB or 4TB cache, have assumed 4TB in Large and 1TB in Medium

**Comment by lawrencegripper** [comment]
Further work has highlighted that these sizes will not be doable in all regions due to the variable availability of different VM SKU's.

Do we whitelist locations we know will succeed and if so how is this maintained? @marrobi

**Comment by marrobi** [comment]
Is there a single configuration that will work for all regions - perhaps add that as a default size? Perhaps do that, then for the other sizes as long as available in UK DCs we are good for testing, and document why sizes may fail?

**Comment by lawrencegripper** [comment]
That becomes a bit of large task, take these `n` SKUs and try them in these `x` regions to find an overlap?

**Comment by lawrencegripper** [comment]
Add a TShirt size for dev deployments which will keeps a single node active in Azure Batch pools

**Comment by lawrencegripper** [comment]
Waiting on #1015 to simplify testing on "Large" and "Medium" builds and respective costs
