### ISSUE TITLE
Update IVA Dockerfile and Init container to work with latest IVA configuration

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1034]
Currently, the IVA Dockerfile uses a Build ARG to build against a specific release of IVA. Different versions of IVA have different configuration so the current init container configuration string replace will not work with other versions of IVA. Also the IVA config pulled in by the init container has to match the same version of the IVA that will be deployed so the configs match.

**Comment by martinpeck** [comment]
@jjcollinge  can you please make sure the title and description reflect the task, and then we can assign elsewhere? Thanks!

**Comment by jjcollinge** [comment]
Updated in #1042 to work exclusively against the latest commit on IVA github or later.

**Comment by jjcollinge** [comment]
Done in #949
