### ISSUE TITLE
Fix Docker Builder pattern

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1035]
The dockerfile should copy the source code from the repository it is in and build that rather than re-cloning the source from a specified branch. This allows us to pin a Dockerfile against a git commit hash and to perform local container builds of the code without having pushed it.

**Comment by martinpeck** [comment]
@jjcollinge can you please make sure the title and description reflect the task, and then we can assign elsewhere? Thanks!

**Comment by jjcollinge** [comment]
Fix in #1042
