### ISSUE TITLE
Pedigree file not found during upload leaves status "uploading"

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#104]
If the user tries to add a pedigree file (don't know if it happens with others) but it is not found in the filesystem, its entry in catalog is still created and the status set as "uploading" and not cleaned up. When re-trying with the correct path, if the file has the same name as the failed one, nothing happens because the entry is already in catalog and it must be manually removed from the database.

A side-effect is that population cohorts can't be created nor the derived statistics calculated.

**Comment by j-coll** [comment]
A file at status "Uploading" refers a file that have been recently created, but have not yet a physical file attached. As you can see in the [File life cycle](
https://github.com/opencb/opencga/wiki/OpenCGA-Catalog#file-life-cycle), a file in this status can reach a **Ready** status by uploading a file.
Using the new command "files upload", you can attach a physical file with the catalog entry file.

As part of the fix, a file exist check is done at the beginning.
