### ISSUE TITLE
Document T-Shirt Size Discussion

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1040]
Take output of discussion and create document.

**Comment by lawrencegripper** [comment]
## Proposal

I've taken a quick look at this and wanted to put my thoughts down on the issue so we can see if this approach meets what others are expecting/thinking. This is a first draft and there are likely better ways to tackle it but I wanted to get the ball rolling. 

Within the template `parameters` we would define and integer based field for `deploymentSize` the description would outline the characteristics of each available size. 

```json
        "deploymentSize": {
            "type": "int",
            "allowedValues": [
                0, 1, 2
            ],
            "defaultValue": 0,
            "metadata": {
                "description": "What size of deployment do you want? 0 = For single researches testing things out. 1 = For x genomics with xgb per sec load rate. 2 = is for x/y"
            }
        },
```

I've gone with `int` as it makes the ARM easier to write and avoids the nasty trend of `extraLarge`, `mega`, `superMega`. In my example the description gives a quick overview on what each option offers. 

Next in the `variables` section of the template we use an array of identical config objects. Each of these represents the configuration of the solution at that size. Then the index is used the pull out the variables and build up the configuration which is later used in the template below. I've deliberately kept the scope of these changes to the `variables` section to keep alteration in the future easier. For example, if we moved away from the approach the `variables` section could be reworked but the `resources` section would remain the same. 

```json
        "sizingOptions": [
            {
                "type": "0 = Small",
                "avereEnabled": false,
                "azureFilesEnabled": true
            },
            {
                "type": "1 = Medium",
                "avereEnabled": false,
                "azureFilesEnabled": true
            },
            {
                "type": "2 = Large",
                "avereEnabled": false,
                "azureFilesEnabled": true
            }
        ],
        "selectedSize": "[variables('sizingOptions')[parameters('deploymentSize')]]",
        "avereEnabled": "[variables('selectedSize').avereEnabled]",
        "azureFilesEnabled": "[variables('selectedSize').azureFilesEnabled]"
```

Then later in the `resources` section the variables `avereEnabled` etc are used. 

```json
{
            "condition": "[variables('azureFilesEnabled')]",
            "resourceGroup": "[parameters('rgPrefix')]",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2018-05-01",
            "name": "azurefiles",
            "dependsOn": [
                "[parameters('rgPrefix')]"
            ],
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "[concat(parameters('_artifactsLocation'), '/azurefiles/azuredeploy.json', parameters('_artifactsLocationSasToken'))]",
                    "contentVersion": "1.0.0.0"
                }
            }
        },
```

**Comment by martinpeck** [comment]
Whiteboard notes: 

![image](https://user-images.githubusercontent.com/1524451/51284901-0b578100-19e5-11e9-9836-6dc079ebfd28.png)

**Comment by martinpeck** [comment]
Whiteboard notes transcribed into a Markdown table:

Component | Property | Small | Medium | Large
-- | -- | -- | -- | --
Avere | use-azure | FALSE | TRUE | TRUE
  | node-quantity | n/a | 3 | 12
  | ssd-per-node | n/a | 4 | 4
  | ssd-size | n/a | 256GB | 1TB
  | node-size | n/a | D16 | E32
  | premium-blob | n/a | ??? | ???
  |   |   |   |  
Solr | vm-size | E54v3 | E8v3 | E16v3
  | vm-quantity | 1 | 2 | 4
  | disk-type | SSD | SSD | SSD
  |   |   |   |  
Batch | node-size | low-priority | F8v2 | ???
  | max-nodes | 5 | 16 | ???
  | jobs-per-node | 1 | 1 | ???
  | disk-type | ??? | SSD | ???
  |   |   |   |  
MongoDB | node-quanity | 1 | 3 | 5
  | node-size | D2v2 | E8v3 | E16v3
  | disk-type | E10 | P20 | P20
  |   |   |   |  
HDInsights | head-node-quanity | 1 | 2 | 2
  | head-node-size | D4v2 | ??? | ???
  | worker-node-quanity | 2 | 20 | 50
  | worker-node-size | A6 | D5v2 | D14v2
  |   |   |   |  
Daemon | node-size | A4 | F8v2 | ???
  | disk-type | ??? | ??? | ???
  |   |   |   |  
Web Servers | node-quantity | 1 | 2 | 4
  | node-size | D2sv3 | D4sv3 | D4sv3
  | disk-type | ??? | ??? | ???

**Comment by martinpeck** [comment]
We appear to have quite a few missing numbers from the table above (the ??? values). I could do with some input into what these should be. Some of them might just be "copy the value to the left", but I didn't want to assume that.

**Comment by lawrencegripper** [comment]
Thanks for writing this up Martin! Here are my thoughts on the `???` items based on memory...

Batch | node-size | low-priority | F8v2 | F8v2
  | max-nodes | 5 | 16 | 1000
  | jobs-per-node | 1 | 1 | 1
  | disk-type | ??? | SSD | SSD
  |   |   |   |  

/\ For batch the only real update for Large was the `max-nodes` field.

Web Servers | node-quantity | 1 | 2 | 4
  | node-size | D2sv3 | D4sv3 | D4sv3
  | disk-type | ??? | ??? | ???

/\ For Web Servers the `disk-type` wasn't significant so would remain constant as standard HDD

HDInsights | head-node-quanity | 1 | 2 | 2
  | head-node-size | D4v2 | ??? | ???
  | worker-node-quanity | 2 | 20 | 50
  | worker-node-size | A6 | D5v2 | D14v2
  |   |   |   |  

/\ For HDInsight the `head-node-size` would remain as `D4v2` for all sizes

Daemon | node-size | A4 | F8v2 | ???
  | disk-type | ??? | ??? | ???
  |   |   |   |  

/\ For the Deamon `node-size` would remain as `F8v2` when Large and `disk-type` would remain as `HDD` throughout

**Comment by martinpeck** [comment]
Thanks @lawrencegripper. So, with those updates:


Component | Property | Small | Medium | Large
-- | -- | -- | -- | --
Avere | use-azure | FALSE | TRUE | TRUE
  | node-quantity | n/a | 3 | 12
  | ssd-per-node | n/a | 4 | 4
  | ssd-size | n/a | 256GB | 1TB
  | node-size | n/a | D16 | E32
  | premium-blob | n/a | ??? | ???
  |   |   |   |  
Solr | vm-size | E54v3 | E8v3 | E16v3
  | vm-quantity | 1 | 2 | 4
  | disk-type | SSD | SSD | SSD
  |   |   |   |  
Batch | node-size | low-priority | F8v2 | F8v2
  | max-nodes | 5 | 16 | 1000
  | jobs-per-node | 1 | 1 | 1
  | disk-type | SSD | SSD | SSD
  |   |   |   |  
MongoDB | node-quanity | 1 | 3 | 5
  | node-size | D2v2 | E8v3 | E16v3
  | disk-type | E10 | P20 | P20
  |   |   |   |  
HDInsights | head-node-quanity | 1 | 2 | 2
  | head-node-size | D4v2 | D4v2 | D4v2
  | worker-node-quanity | 2 | 20 | 50
  | worker-node-size | A6 | D5v2 | D14v2
  |   |   |   |  
Daemon | node-size | A4 | F8v2 | F8v2
  | disk-type | HDD | HDD | HDD
  |   |   |   |  
Web Servers | node-quantity | 1 | 2 | 4
  | node-size | D2sv3 | D4sv3 | D4sv3
  | disk-type | HDD | HDD | HDD

That just leaves `???` for the Avere `Premium Blob`. It wasn't clear if this was written on the board as a property, or just a question for the room. @marrobi : do you recall?

**Comment by martinpeck** [comment]
Once we're happy with this, do we want this as a .xlsx, a .md file, or somewhere else?

**Comment by marrobi** [comment]
Was a  question, maybe one for out Avere expert, @lawrencegripper  to investigate.

**Comment by marrobi** [comment]
And should be in documentation  somewhere I would think.

**Comment by lawrencegripper** [comment]
I'd say we keep it here as it'll shortly be captured in the code anyway and any other doc would just drift from reality. 

I've emailed the Avere team regarding Premium Blob but this shouldn't block us, for now lets assume it's not-supported and we can add it in in the future if it is supported. Sound like a plan?

**Comment by martinpeck** [comment]
I was worried about the same thing, but also just added it to the README.md within the `arm` folder.

I suggest we commit it for now, so we can use it for discussion, and then determine if there's a way to prevent that drift (even if it's just a pointer to the section in the ARM templates, rather than a table). 

I think having something in the docs that says "we have this concept of t-shirt sizes, and this is what they mean" is useful, but I agree re the drift issue.

**Comment by lawrencegripper** [comment]
@martinpeck you've won me over - MD in the Readme makes sense as users are going to want to review and they're unlikely to read the ARM

**Comment by martinpeck** [comment]
Merged. Closing. Thanks all.
