### ISSUE TITLE
The WS "fetch" from FileWSServer returns empty fields.

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#105]
The WS "fetch" from FileWSServer returns empty fields.

These fields are "annotation.effects" and "annotation.frequencies".

Example: 
```json
conservedRegionScores: [
   {
      "score": 0.5329999923706055,
      "source": "phylop",
      "description": ""
  },
  {
     "score": 0.9819999933242798,
    "source": "phastCons",
    "description": ""
  }
],
"effects": { },
"frequencies": { }
```

**Comment by imedina** [comment]
These are old fields from annotation data model. They were kept for compatibility reasons and scheduled to be removed. This issue is timely, this will removed in next release. It is not a bug, changing  label to Task.

**Comment by aaleman** [comment]
Ok.
The Population Freqs will be removed from the schema or they will be moved to another location (maybe to a new field)?
How could we filter by those population freqs?
We think this is a very important and useful filter.

Thank you.

**Comment by j-coll** [comment]
Population Frequency filters added on issue #159
