### ISSUE TITLE
Deploying the azure branch throws a DNS conflict

### ISSUE THREAD

**Issue by avodovnik** [opencb/opencga#1051]
When deploying the `azure` branch, I keep getting the same `BadRequest` saying `DnsRecordInUse`, specifically: `DNS record webserverspxcabn.westeurope.cloudapp.azure.com is already used by another public IP.`.

I thought this name was randomly assigned - but that doesn't seem to be the case. 

Full ARM error:

```json
Deployment failed. Correlation ID: adae8ccf-0597-41b9-9cf9-bbbea17426ee. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"DnsRecordInUse\",\r\n    \"message\": \"DNS record webserverspxcabn.westeurope.cloudapp.azure.com is already used by another public IP.\",\r\n    \"details\": []\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
```

**Comment by lawrencegripper** [comment]
This looks like it's my bad - the unique string is incorrectly generated in the top level template based off the resource group name https://github.com/opencb/opencga/blob/azure/opencga-app/app/scripts/azure/arm/azuredeploy.json#L208

We need to move this unqiue string generation into the `webserver` template like we do with clusterName for HDInsights here: https://github.com/opencb/opencga/blob/azure/opencga-app/app/scripts/azure/arm/hdinsight/azuredeploy.json#L149

**Comment by avodovnik** [comment]
Ah, thanks for the pointer @lawrencegripper! I'll go ahead and fix it. I need to deploy anyway :-)

**Comment by martinpeck** [comment]
This work is now covered by Issue #1023 and PR #1048, so closing it now.
