### ISSUE TITLE
Publish docker images from Jenkins pipeline

### ISSUE THREAD

**Issue by jjcollinge** [opencb/opencga#1056]
Follow up issue to #1042 
Currently the Jenkins build pipeline only builds the docker containers. In order to publish these images for releases a some arguments need to be provided to Make.

`make DOCKER_USERNAME="<insert docker username>" DOCKER_PASSWORD="<insert docker password>" TAG="<insert tag>" PUBLISH=true -f opencga/app/scripts/docker/Makefile`

TAG is optional - it will default to the git commit SHA but you can override it to tag the docker images with version/release numbers if you wish.

If you want to use a private docker registry you can also provide:
- DOCKER_REPO
- DOCKER_SERVER

These values should be provide by the build env - DOCKER_PASSWORD should be set a secret if possible.

**Comment by jjcollinge** [comment]
@wbari in relation to your message on #1042 

I think the Jenkins script looks good. 

Before I go on, I want to stress that as you guys are maintaining this you need to make sure you are comfortable with the process and tooling.

I have some thoughts, which I'll note down below just for reference.

I appreciate that the sample Jenkins script you pasted was really just a quick example of how it may look. I just wanted to flag a few things for consideration.

- Using existing builds to avoid rebuilding OpenCGA both outside and inside the container
- Build contexts, need to be set to the repository root to ensure the `build` and `src` can be copied/mounted into the containers correctly
- Having roughly the equivalent logic in both the Makefile/scripts and Jenkinsfile requires more maintenance to keep them in sync.
- The local development experience (`make`) will differ to how the build environment works
- Jenkins credentials and variables can still be used with the Makefile by passing them into the Make command as shown above. No passwords need to be incldued in the Makefile themselves.
- Using the Makefile would condense the Jenkinsfile stage to a single line

However, using the Makefile in its current form would not allow you to have 2 separate stages (build and publish).

I am not precious about either solution and want to make sure you pick something you're happy working with going forward. Hope that makes sense :) happy to discuss further.

**Comment by wbari** [comment]
Thanks @jjcollinge  for prompt reply. I have discussion here with opencga team as well for going forward, we think its best that at least we separate the "publish" step from that make/build scripts as a jenkin stage as its more logical and kind of common practice and gives quick glance in case of failure of each steps separately visually.

For building images, that true we ll remove loop from jenkins pipeline build step, my personal opinion is build step and logic should be together as rest of all the steps, branchName, Tag name etc fields which we need are already available and build has already been completed. The context is set properly and it points to root dir "opencga" ( as you can see from other jenkin job's steps stage ('Validate ARM Templates')  ... sh 'cd opencga-app/app/scripts/azure/arm && ...) But for now I don't mind to call the makefile from that step, reduce the size of lines there and later we can improve it either by adding a maven plugin to build docker images from Dockerfiles than using shell script which will also help the local build. Meanwhile we got your scripts, they are perfectly fine, well documented, any user prefer to use them can use.

**Comment by jjcollinge** [comment]
@wbari makes sense! I think that's a good route

**Comment by wbari** [comment]
#1061
