### ISSUE TITLE
Migrate Makefile from recursion to sub Makefile(s)

### ISSUE THREAD

**Issue by jjcollinge** [opencb/opencga#1058]
Currently the Docker Makefile has a default build target `build-all` - this target calls a bash script `build-all.sh` which then makes multiple invocations of the original Makefile to invoke a different build target. As we are using so many variables within the Makefile it'll likely be easier to control the environment if we split the top level Makefile from sub Makefiles.

**Comment by martinpeck** [comment]
Closing cos we think it's done.
