### ISSUE TITLE
QueryParams "sift" and "polyphen" do not work in Fetch WS.

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#106]
These options (sift & polyphen) do not filter when we call that Web Service. The WS always returns the same number of variants.

We are using the options from the file ```VariantDBAdaptor```. 

Example URL:

http://test.url.com/opencga/rest/files/181/fetch?polyphen=0.5&region=&skip=0&limit=10&sid....

http://test.url.com/opencga/rest/files/181/fetch?sift=0.5&region=&skip=0&limit=10&sid....

**Comment by imedina** [comment]
The links seem to be wrong, when I click on them the following URL is opened:

http://www.coolchaser.com/?polyphen=0.5&region=&skip=0&limit=10&sid

**Comment by aaleman** [comment]
These are dummy urls.

**Comment by j-coll** [comment]
sift and polyphen are "operational filters".
To query by this values, use:

`[polyphen|sift] = <op><float>`
`<op> : [<|<=|>|>=|==|=]`


So, the query will result in something like:
`http://test.url.com/opencga/rest/files/181/fetch?polyphen=>0.5&sid....` polyphen > 0.5
`http://test.url.com/opencga/rest/files/181/fetch?sift=%3D0.5&sid...` sift = 0.5

*** Take in mind that the character "=" must be encoded into `%3D`
