### ISSUE TITLE
Ensure that indices are created in mongo

### ISSUE THREAD

**Issue by jmmut** [opencb/opencga#108]
It's not clear if we are creating indices consistently in all branches and in all the collections that need them.

For example, in 0.5 currently there are no indices in `variants` collection.

**Comment by cyenyxe** [comment]
At least these indexes need to be created: https://github.com/opencb/opencga/blob/088560e91b94f716f088fe354628df2f81805b58/opencga-storage/src/main/java/org/opencb/opencga/storage/variant/mongodb/VariantMongoWriter.java#L232

The ones for the annotation and statistics still need to be decided.

**Comment by j-coll** [comment]
Due to schema changes, `_at.gt` and `_at.ct` are not longer needed.
The correct indexes will be:
 * `annot.xrefs.id` for all external names (gene, transcript, rs, ss... ) 
 * `annot.ct.so` for consequenceType soAccesion

**Comment by j-coll** [comment]
Other interesting annotation indexes could be:
 * `annot.ct.polyphen.sc`
 * `annot.ct.sift.sc`
 * `st.maf` 
 * `st.mgf`
