### ISSUE TITLE
Webservers Cloud-Init doesn't wait on configuration initialization

### ISSUE THREAD

**Issue by jjcollinge** [opencb/opencga#1082]
The Webservers ARM resources is dependent on the Daemon VM ARM resource but this doesn't handle waiting for the initialisation scripts to complete on the Daemon VM before starting the containers on the web servers.

The long term solution to this we think will be to write an ARM custom script extension that checks the status of the cloud-init scripts - this will make the ARM level dependencies respect the execution of the scripts.

However, a short term solution is needed to ensure reliability of the deployment.

**Comment by marrobi** [comment]
@jjcollinge this can be closed?
