### ISSUE TITLE
Attach separate (non-OS) managed SSD to MongoDB VMs for data storage

### ISSUE THREAD

**Issue by bart-jansen** [opencb/opencga#1089]
Additional to https://github.com/opencb/opencga/pull/1074, all MongoDB data should be stored on separate mounted Premium SSDs

**Comment by avodovnik** [comment]
@bart-jansen let me know if you want me to add the data disk through the ARM template

**Comment by bart-jansen** [comment]
@avodovnik would be great! I'll focus on the mounting/config parts of it then
