### ISSUE TITLE
Create ARM Based Deployment "Stub" that kicks off Terraform Deployment of OpenCGA

### ISSUE THREAD

**Issue by martinpeck** [opencb/opencga#1092]
ARM Stub needs to enable Market Place deployment, while allowing the engineering work to take place in Terraform.

Questions:

- How would outputs be presented to a marketplace user?
- How would progress be presented to a marketplace user?

**Comment by jjcollinge** [comment]
Current status update. Created a custom Dockerfile that builds on the `hashicorp/terraform:light` image with the addition of the template to deploy. Then use an ARM template to create an identity, give attach a subscription level role assignment and then start the ACI container using the above image injecting parameters as Terraform command line args. Current sticking point, it is not possible to assign a subscription level role assignment from a ARM template deployment see issue: https://github.com/MicrosoftDocs/azure-docs/issues/17715

**Comment by jjcollinge** [comment]
Also when using an MSI with ACI you need to consider the AAD identity service prinicpal propagation issue. This doesn't appear to be handle in ARM yet and will result in a `PrincipalNotFound` error being returned if the role assignment is attempted before the principal has propagated fully.

**Comment by marrobi** [comment]
Could the ARM template create storage before spinning up the ACI instance?

**Comment by jjcollinge** [comment]
Yeh something like that (it makes me want to claw my own eyes out) - although it's not a guarentee as when AAD is slow-er than nroaml it doesn't seem to be delayed long enough. I'm currently just deploying a additional random storage account to delay things but it's not a long term solution.

**Comment by marrobi** [comment]
I mean for the terraform state. Sorry, no threading :)

**Comment by jjcollinge** [comment]
oh right, terraform state isn't an issue it just depends on what user experience we want to expose. I'm guessing we want state to be in a storage account and the creds output from the ARM deployment so you can hook up terraofmr and start managing the OpenCGA terraform deployment directly. But was wondering if bypassing ARM it'd cause consistency issues with redeployments of ARM. Think it's not a problem just havent discussed it yet.

**Comment by marrobi** [comment]
So, summarising the things we discussed, I think:
1. ACI/Azure Deployment needs to wait for the terraform deployment to complete
2. Outputs should be surfaced through ARM - in this instance they may be able to be statically created - just a FQDN or two?.
3. Agree Terraform state should be accessible for those who want to utilise it.

Anything else?

**Comment by jjcollinge** [comment]
I guess 1 way we can make ARM wait and get outputs from terraform is to change ACI to a VM with Custom Script extension... would slow deployment and be more heavy weight but would give us more control

**Comment by jjcollinge** [comment]
Summarizing options:

Use Virtual Machine to run Terraform deployment via a custom script extension.
+ Synchronous deployment i.e. ARM will return only when the custom script extension has completed
+ Output available directly in ARM outputs
- Requires deploying a VM, Network, NIC, etc. so bigger overhead on existing deployment
- Requires additional clean up to remove these resources or pay for them to be idle

Use ACI to deploy terraform directly.
+ Small overhead on existing deployment
+ Only pay for use
- Cannot easily expose dynamic outputs directly as ARM outputs
- Deployment is asynchronous so ARM may return success in 2 minutes but terraform fails after 15 mins in the background
- Likely requires user to use terraform tools directly to inspect state, make modifications, etc.

Use Deploy to Azure service http://github.com/jjcollinge/terraform-deploy-to-azure
+ Small overhead on existing deployment
+ Terraform trace visible in web view
+ Terraform outputs visible in web view
+ Small overhead on existing deployment
- Additonal components to manage
- Non standard deployment

**Comment by lawrencegripper** [comment]
@jjcollinge thanks for writing up the options, my initial reaction is that the last (TF Deploy to Azure) will give the nicest user experience during a deployment but as you say this does come with additional complexity. 

I think we need more of the team to have a review of these options then have a chat through in more detail.

**Comment by marrobi** [comment]
Very useful. Does the third option work with marketplace?

**Comment by jjcollinge** [comment]
@marrobi with a little tweaking it should yes

**Comment by martinpeck** [comment]
Closing this issue, and removing it from the `azure` project on GitHub, as part of #1208 tasks to wrap up and tidy up the Terraform work.
