### ISSUE TITLE
HDInsight Output Subnet references the Default one

### ISSUE THREAD

**Issue by avodovnik** [opencb/opencga#1096]
Looking at the outputs code from the `vnet` template, the `hdinsightSubnetId` referneces the default one, instead of the one created for hdinsight. Is this intentional? 

```
"hdinsightSubnetId": {
   "type": "string",
   "value": "[reference(resourceId('Microsoft.Network/virtualNetworks', 'vnet')).subnets[0].id]"
},
```

**Comment by avodovnik** [comment]
@marrobi and @lawrencegripper could you take a look if this is intentional?

**Comment by lawrencegripper** [comment]
I think this was just a quick solution as they're isn't a subnet for HDInsight so the output points to the default but would allow us to add one if we wanted too. 

Maybe best option is to add a subnet for HDInsight and update this reference to it.

**Comment by avodovnik** [comment]
I remember @marrobi mentioning there is a "special case" in how HDInsight works, and that's why things get deployed there. But I'm happy to take this on once I finish the NSG work.

**Comment by j-coll** [comment]
HDInsight is using its own subnet now
