### ISSUE TITLE
opencga-batch image not on docker hub

### ISSUE THREAD

**Issue by marrobi** [opencb/opencga#1102]
This image is not appearing, is Jenkins building and pushing?

**Comment by wbari** [comment]
The last push was 23 min ago from Azure Branch (56797bc464b9e0fc668e298d41b34735ee0a9c4b). @marrobi could you please share the tag you are looking and  i double check on dockerhub. Currently Jenkins is running Azure branch tests, which takes some time ( 2-3 hours ) I can kill and run your specific PR/Job if you let me know.

**Comment by marrobi** [comment]
Apologies, forgot we are working with Jenkins files. The batch PR was merged a few days ago, but been using my images until today when switching to oracle images. 

Does it just need adding to this array?  

```def images = ["opencga", "opencga-app", "opencga-daemon", "opencga-init", "iva"]```

If so I can do a separate PR.

**Comment by wbari** [comment]
Have we created new image called **"opencga-batch",** if so that need Jenkins file update, could you please share the branch or PR where you did so i can update jenksfile ?

**Comment by wbari** [comment]
Yes, we need to add in that array.

**Comment by marrobi** [comment]
It was #1081 - let me know if you can do it easily, otherwise I will create  a PR.

**Comment by wbari** [comment]
I will do it and merge to Azure branch. These will be new images : (opencga opencga-app opencga-daemon opencga-init opencga-batch iva)
