### ISSUE TITLE
VepVariantAnnotator hangs when an exception occurs

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#111]
If the VEP file used as input is not found, the following exceptions are displayed: http://pastebin.com/cAMW0vQh, but the application is not aborted, it just hangs.

**Comment by imedina** [comment]
I'm closing this since Ensembl VEP is not longer officially supported since there doesn't seem to be demand or anybody interested in supporting it. This might be reopened if needed.

**Comment by ldemaeztu** [comment]
As discussed some weeks ago, we are interested in being able to load annotations done with Ensembl VEP. Any plans to support VEP again? Any clues on what needs to be fixed to make it work again? Thanks!
