### ISSUE TITLE
Adapt OpenCGA Daemon to recover from hang over and avoid inconsistent state.

### ISSUE THREAD

**Issue by wbari** [opencb/opencga#1117]

**Comment by lawrencegripper** [comment]
Can we combine this with a `HEALTHCHECK` annotation to the container to have it identify if it's hung? I've not used it before but may do the trick. 

https://docs.docker.com/engine/reference/builder/#healthcheck

@marrobi @jjcollinge - you seen this before?

**Comment by wbari** [comment]
@lawrencegripper  That's good one. Actually our daemon container don't hang fully, only one of the threads inside that daemon only hangs with mongo call and rest of the daemon works fine. I ll look more into this and may be do some grep on logs to make a kind of health check if that workable I will add that on docker side. In any case after these changes, restart of container will be safe and automatic.

**Comment by lawrencegripper** [comment]
Sounds good, looks like we'd need to add [this `autoheal`](https://hub.docker.com/r/willfarrell/autoheal/) container to the nodes running the docker instances so that `unhealthy` nodes are restarted.
