### ISSUE TITLE
TF Migrate: Solr/Zookeeper

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#1122]
Migrate Solr and Zookeeper to native TF Scripts

**Comment by lawrencegripper** [comment]
I'm now also working on this migration alongside #1124 so I can be productive while waiting on test results from #1124

**Comment by martinpeck** [comment]
Closing this issue, and removing it from the `azure` project on GitHub, as part of #1208 tasks to wrap up and tidy up the Terraform work.
