### ISSUE TITLE
TF Migrate: Log Analytics

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#1124]
Investigate how best to handle in TF. Options:

- ARM Wrapper
- Local Exec and Azure CLI
- TF (May require changes to AzureRM provider in TF)
- Other

**Comment by lawrencegripper** [comment]
Looks like we'll be able to handle this natively with [this resource](https://www.terraform.io/docs/providers/azurerm/r/monitor_diagnostic_setting.html)

**Comment by lawrencegripper** [comment]
Hmmm looks like we might be missing a way to configure the [`dataSources`](https://github.com/terraform-providers/terraform-provider-azurerm/issues/931#issuecomment-412909251) element of the LogAnalytics workspace... just digging into it a bit more

**Comment by lawrencegripper** [comment]
This work will be completed as a mix of TF and wrapped ARM with a view to fixing this in the future with a contribution to TF see #1129

**Comment by lawrencegripper** [comment]
Currently paused work to focus on other issues

**Comment by martinpeck** [comment]
Closing this issue, and removing it from the `azure` project on GitHub, as part of #1208 tasks to wrap up and tidy up the Terraform work.
