### ISSUE TITLE
Create PR on IVA repo to to build and publish docker image

### ISSUE THREAD

**Issue by marrobi** [opencb/opencga#1147]
A new docker image should be published on an IVA release. At present IVA is published as part of OpenCGA.

Create a PR with docker assets and jenkins file to build and publish.

**Comment by wbari** [comment]
merged all changes on IVA develop. SHA bb49d8733cfa850b1a5a06a78f6a154212a9213d ( Jenkinsfile, Dockerfile, docker build, docker publish to docker hub with latest tag)
