### ISSUE TITLE
Should Avere templates consume the official templates, rather than having our own "version".

### ISSUE THREAD

**Issue by marrobi** [opencb/opencga#1166]
Currently the Avere templates live in this repository. there are "official" templates here: https://github.com/Azure/Avere/tree/master/src/vfxt . 

If the "official" templates are updated this project will not get the fixes/improvements.

@lawrencegripper points out reasons why they were not used initial are:
- We need a different VNet configuration
- Concerns around RBAC

@lawrencegripper can you clarify.

**Comment by lawrencegripper** [comment]
I've created an issue to ask for their plans around versioning the upstream templates: https://github.com/Azure/Avere/issues/315

**Comment by lawrencegripper** [comment]
So I've attempted to try this out here: https://github.com/opencb/opencga/pull/1181

Things to note, the template only allows the use of `Standard_E32s_v3` machines and requires at minimum 3 of them so 96 cores.

**Comment by lawrencegripper** [comment]
So it looks like this also fails with the following error, this looks like a permissions/roles issue. 

```
 Role avere-cluster not found\\n2019-02-20T17:06:26+0000 - vfxt:ERROR - Role avere-cluster not found\\n2019-02-20T17:06:26+0000 - vfxt:ERROR - Failed to create cluster
```

It looks like we'd need a manual step before deployment to create this role. 

```
vFXT.msazure:DEBUG - Creating connection of type authorization\\n2019-02-20T17:06:21+0000 - vFXT.msazure:DEBUG - No such role: avere-cluster\\n2019-02-20T17:06:22+0000 - vFXT.msazure:WARNING - Failed to lookup role avere-cluster, retrying\\n2019-02-20T17:06:23+0000 - vFXT.msazure:DEBUG - No such role: avere-cluster\\n2019-02-20T17:06:24+0000 - vFXT.msazure:WARNING - Failed to lookup role avere-cluster, retrying\\n2019-02-20T17:06:24+0000 - vFXT.msazure:DEBUG - No such role: avere-cluster\\n2019-02-20T17:06:25+0000 - vFXT.msazure:WARNING - Failed to lookup role avere-cluster, retrying\\n2019-02-20T17:06:25+0000 - vFXT.msazure:DEBUG - No such role: avere-cluster\\n2019-02-20T17:06:26+0000 - vFXT.msazure:ERROR - Failed to create nodes: Role avere-cluster not found\\n2019-02-20T17:06:26+0000 - vfxt:ERROR - Role avere-cluster not found\\nTraceback (most recent call last):\\n  File \\\"/usr/local/bin/vfxt.py\\\", line 725, in main\\n    cluster = Cluster.create(service, args.instance_type, args.cluster_name, args.admin_password, **options)\\n  File \\\"/usr/local/lib/python2.7/dist-packages/vFXT/cluster.py\\\", line 304, in create\\n    service.create_cluster(c, **options)\\n  File \\\"/usr/local/lib/python2.7/dist-packages/vFXT/msazure.py\\\", line 1478, in create_cluster\\n    raise vFXTCreateFailure(e)\\nvFXTCreateFailure: Role avere-cluster not found\\n2019-02-20T17:06:26+0000 - vfxt:ERROR - Role avere-cluster not found\\n2019-02-20T17:06:26+0000 - vfxt:ERROR - Failed to create cluster\\```

**Comment by lawrencegripper** [comment]
The avere team have come back on that issue and are investigating pinning a release of the template to a `vfxt` release. This would allow us to pin to both an ARM template and the version of Avere it deploys hopefully making it viable to use the upstream as we wouldn't see breaking changes.

**Comment by martinpeck** [comment]
Need to compile list of questions for Avere team, and then we probably need to set up a call with them.

**Comment by lawrencegripper** [comment]
Closing as we're moving Avere deployment out of the template #1207
