### ISSUE TITLE
File list Web service returns ".deleted_*" files.

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#119]
When I delete a file using "File/delete" web service the file is removed from disk.
But when I call File/list web service it returns ".deleted_" files. Is that correct? 
I guess the Web service should not return ".deleted" files, should it?

Test url:
http://test.babelomics.org/opencga/rest/files/63/list?sid=sYtbUHw0cJ3xc7yIAnAV&studyId=59

**Comment by j-coll** [comment]
These WS returns all files within the folder 63.

Use http://test.babelomics.org/opencga/rest/files/63/list?sid=sYtbUHw0cJ3xc7yIAnAV&statys=READY,STAGED,MISSING to avoid `TRASHED` and `DELETED` files.
FYI: The query param "studyId" is not really needed.

**Comment by aaleman** [comment]
Thanks.
Where could we found information about all this options?

**Comment by j-coll** [comment]
We are now working to improve the Catalog Querying API, which will include queries for free fields like "attributes" or "config", and operational queries like `files.size ``>`` 4000` or `files.name ``=~`` *.vcf`

This work will finish with a well defined and documented query API for Catalog.

In this moment, most of the query params are on the [Swagger API web page](https://github.com/opencb/opencga/blob/43c14d4ab170c0611fa23560233ec800caf08bbf/opencga-server/src/main/java/org/opencb/opencga/server/FileWSServer.java#L501). 

By the way, the Swagger non working problems will be fixed soon. #116
