### ISSUE TITLE
R Package - Error: lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#1192]
It looks like the R client is out of date with the current API, is that correct? 

Can the R package be updated to fix this issue? Or is there something I am missing here?

```
> project <- projectClient(con, project='new-project', action='create')
[1] "URL: http://localhost:8080/opencga-1.4.0-rc2/webservices/rest/1.0.1/projects/create?skip=0"
Error: lexical error: invalid char in json text.
                                       Unrecognized field "limit" (cla
                     (right here) ------^
```

Thanks!

**Comment by imedina** [comment]
Many thanks for reporting!

R client should be synced with REST in branch _release-1.4.0_, we will fix this week.

**Comment by nicholsn** [comment]
thanks!

**Comment by pfurio** [comment]
For some reason, I was unable to reproduce exactly your issue. However, I did see other issues that might be somehow related to yours and that prevented me from being able to create a project using the R client.
I already applied that fix in 75a26178bc0b10265bdb866fe28c39df7b93fa83 in branch 'release-1.4.0'. Hopefully, you will now be able to create new projects.

Below you can find an example of how the command would look like:
`projectClient(con, "project1", "create", list(name="Project 1", organism=list(scientificName="Homo sapiens", assembly="GRCh38")))`

Please let me know if you find any further issues.

**Comment by nicholsn** [comment]
@pfurio, thanks for looking into this. I just tested and can confirm that it is now working. Will raise another issue if I run into anything else.

**Comment by melsiddieg** [comment]
Hi everyone, This issue still affects other clients, like familyClient it give the same error when trying to create a new family. it seems to me that the params argument is not handled correctly

output error
familyClient(con, action = 'create', params = list(study='motalla', family="mot_family"))
[1] "URL: http://localhost:8080/opencga-1.4.0-rc2/webservices/rest/v1/families/create?skip=0&limit=2000"
Error: lexical error: invalid char in json text.
                                       Unrecognized field "study" (cla
                     (right here) ------^
Called from: parse_string(txt, bigint_as_char)
