### ISSUE TITLE
Move to 4 cores for Azure Batch

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#1196]
Testing indicates that `Standard_D4s_v3     CPU: 4     RAM:16` is the correct sizing for these nodes.

**Comment by wbari** [comment]
Ran multiple jobs with 4 CPU and 16 GB Ram, went quite fine. CPU was 100% utilised during transformation and rest of the process was quite normal. Around 60% of Ram was in use ( 10 GB). Max file size indexed was 850 MB from Platinum data set.
