### ISSUE TITLE
OpenCGA dev branch produces error when compiling

### ISSUE THREAD

**Issue by justinpaschalldna** [opencb/opencga#120]
I just cloned from github "git clone ........." and ran:

mvn clean install -DskipTests

in datastore and biodata
that worked fine.

But running for OpenCGA I get:
[INFO] Reactor Summary:
[INFO] 
[INFO] opencga ........................................... SUCCESS [0.228s]
[INFO] opencga-core ...................................... FAILURE [27.107s]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project opencga-core: Fatal error compiling: invalid target release: 1.8 -> [Help 1]

is it expected that the dev branch should compile or am I doing something wrong?

**Comment by imedina** [comment]
Looking at [ERROR] message:
Fatal error compiling: invalid target release: 1.8 -> [Help 1]

it seems you are using Java 7, you need Java 8 to compile 'develop' branch as it is said  README at https://github.com/opencb/opencga. Also, keep in mind Java 7 is not longer supported. I have reproduced that error with Java 7 and compile it in Java 8.

As explained in the README, both 'master' and 'develop' branches must compile, and 'master' dependencies are ensured to be at Maven Central Repository. For 'develop' branch dependencies may be cloned and built.

I hope this helps. I close the issue as it seems solved.
