### ISSUE TITLE
Enhancement: Deleted status for job bean

### ISSUE THREAD

**Issue by roalva1** [opencb/opencga#123]
It would be interesting to add the status <pre>DELETED</pre> to org.opencb.opencga.catalog.beans.Job, for reasons like:
1. Recover a deleted job
2. If there is a bug somewhere we don't delete something not requested (currently this happens)

I also ask if add another status <pre>DELETING</pre> would be useful, I leave this to the main developers consideration.
Could it be added to the 0.6.0?

**Comment by j-coll** [comment]
The `DELETED` status is a good idea, and matches with the file behavior. Will be added for the **v0.6.0**

What will be the `DELETING` status for? By the way, the `DELETING` status has been renamed to `TRASHED` for the files. See [Job life cycle](https://github.com/opencb/opencga/wiki/OpenCGA-Catalog#job-life-cycle) and [File life cycle](https://github.com/opencb/opencga/wiki/OpenCGA-Catalog#file-life-cycle) for more information.

**Comment by pfurio** [comment]
All the statuses mentioned have been created. The life cycle has changed slightly and will be documented soon. The new status can be seen [here](https://github.com/opencb/opencga/blob/release-0.8.0/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/File.java#L117)
