### ISSUE TITLE
Question: what stands for file status?

### ISSUE THREAD

**Issue by roalva1** [opencb/opencga#126]
It could be nice to write in the documentation the file status description unless it is not somewhere else, for instance it is not so clear which is the difference between trashed and deleted file, I could imagine, but still, I find a small description needed. Maybe here  https://github.com/opencb/opencga/wiki/OpenCGA-Catalog#file-life-cycle?

**Comment by j-coll** [comment]
The [File Life Cycle](https://github.com/opencb/opencga/wiki/OpenCGA-Catalog#file-life-cycle) documentation has been improved.
