### ISSUE TITLE
Add missing SampleIndex command line operations

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#1282]
The SampleIndex in storage-hadoop may be ported to storage-mongodb at some point. Now, some operations needs to be pushed to the abstract VariantStorageEngine, and, therefore, to the command line.

The new command lines are:

- [x] Annotate the SampleIndex : This operation is executed after the variant annotation, but a reannotation is needed after changing the version of the annotation.
  ```bash
  opencga-analysis.sh variant sample-index
  ```

- [x] Build the FamilyIndex : This operation already exists under the name of "mendelian-errors". Should be, at least, renamed.
  ```bash
  opencga-analysis.sh variant family-index --family [ all | famil1,famil2,...familyN ]
  ```

**Comment by imedina** [comment]
Two comments here:
1. which are the parameters of _sample-index_?   Can we pass a list of samples? all samples?
2. I wonder if the _sample-index-annotate_ should be part of _sample-index_ with a specific parameter

**Comment by imedina** [comment]
Also, we should add documentation about the new operations before closing this issue:

http://docs.opencb.org/display/opencga/Variant+Storage+Operations
