### ISSUE TITLE
How to give permissions to user * for the project and studies

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1331]

**Comment by pfurio** [comment]
That would depend on what permissions you actually want. If you only want any non authenticated user to have access to one study and not the data within (samples, files, etc), you would need to run the following cli:
`opencga.sh studies members-update --action ADD --study {study} --users '*'`

If you also want any non-authenticated user to have access to all the data within a study, you will run the following:
`opencga.sh studies acl-update --action ADD --study {study} --member '*' --template view_only`

Bear in mind that it is not possible to explicitly assign read permissions for projects. Whenever you are giving permissions to any user for one study, you are also implicitly granting read access for the project owning the study.

**Comment by Mohammedhusen** [comment]
Hi,

Thanks for quick response.
command:
./opencga.sh studies acl-update --action ADD --study test_study --member '*' --template view_only
Now am getting this error.

ERROR: unknown top level operator: $isolated

**Comment by pfurio** [comment]
OpenCGA 1.3.x supports MongoDB 3.6.x but it does not support MongoDB 4.0.x which seems to be the one you are using at the moment. You will need to downgrade your DB so that the cli works.

We will add support for MongoDB 4.0.x for next OpenCGA version 2.0.0.

**Comment by Mohammedhusen** [comment]
Thank you!
