### ISSUE TITLE
How to load clinical data into OpenCGA

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1332]
Hi Team,

Could you please share the step to load the clinical data into OpenCGA.

Thanks a lot for your support.

**Comment by pfurio** [comment]
Hi, you have some documentation here:
http://docs.opencb.org/display/opencga/Clinical+Data

and also a small tutorial here:
http://docs.opencb.org/display/opencga/Working+with+Clinical+Data

Please, let me know if you still have any  doubts and I will try to improve the documentation.

**Comment by Mohammedhusen** [comment]
Thanks for sharing the documents we followed and it worked fine.

But is there any option to load bulk data instead of doing one by one individual?
And how does the sample is linked to an individual in this case?

We could see samples field in the collection **individual** but it is loaded as blank.

Should we follow a specific order of loading to get this integration of sample and individual?

Thanks a lot, your continued support really appreciated!

**Comment by pfurio** [comment]
Actually I have realised of quite a few things we are not yet supporting in the CLI that we need to support. I have created this ticket to apply the changes ASAP https://github.com/opencb/opencga/issues/1337

There is no way you can bulk update the clinical data of multiple individuals. You need to go one by one. 
Ideally, if what I thought was implemented had been there, it would be trivial for you to create an individual passing the annotations and the related samples information. You need first to create a register all the samples you want to associate to the individuals you will create later. Secondly, you will need to create the individuals passing the list of samples you want to associate the individuals with. Lastly, you will register the clinical data associated to the individual. It will be something like:

```
opencga.sh individuals create --id {individualId} --samples {samples} [additional fields]
opencga.sh individuals annotation-sets-create --annotation-set-name {individualAnnotName} --annotations {annotations.json} --id {individualId} --variable-set-id {variableSetId}
```

**Comment by Mohammedhusen** [comment]
Thank you!
