### ISSUE TITLE
Rename file using WS

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#135]
How could I rename a file using Web service? Is it possible?

Thanks.

**Comment by j-coll** [comment]
There is no web service for that operation. Needs to be implemented.

**Comment by imedina** [comment]
That's a good idea, although I'm not sure if we should allow all the operations over files using web services. One question, should we implement an 'files/{id}/update' endpoint for all these operations?

**Comment by j-coll** [comment]
Now exists the `.../files/{fileId}/modify` where you can modify almost every field. I like the idea of using the same endpoint.
In this case, **rename** a file should be done with `.../files/{fileId}/modify?name={newName}`, which will call to [`CatalogManager.renameFile(int fileId, String newName, String sessionId)`](https://github.com/opencb/opencga/blob/4911ad424f39931d8ea324c0a7ebcb4f7935cede/opencga-catalog/src/main/java/org/opencb/opencga/catalog/CatalogManager.java#L507)

In a similar way, **move** a file should be done with `.../files/{fileId}/modify?path={newLocation}`
But, in this case, there is no implementation for this operation yet. A new ticket needs to be opened for this operation.

**Comment by aaleman** [comment]
Thanks for the info, but:

we built the URL as you said
http://bioinfoint.hpc.cam.ac.uk/opencga/rest/files/261/modify?sid=I0RQGFjoIouT32MMMwnU&name=newName
 and we got this error:

```
errorMsg: "Parameter 'name' can't be changed directly. Use "rename" instead",
```


So, we replaced 'name' by 'rename':
http://bioinfoint.hpc.cam.ac.uk/opencga/rest/files/261/modify?sid=I0RQGFjoIouT32MMMwnU&rename=newName

and we got this new error:
```
errorMsg: "Parameter 'rename' can't be changed. Requires admin account",
```

**Comment by j-coll** [comment]
I'm sorry, I think there was a misunderstanding.
There are not a rest operation for renaming or moving files yet. My last post was an idea of how it could be implemented using the `modify` operation.

**Comment by aaleman** [comment]
Hi!
Do you have any more info about this issue?
Thanks!

Related: #136
