### ISSUE TITLE
ERROR: Error creating directory file:///mongodb/mongodbweb1/opencga/sessions/ with parents=true

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1373]
Hi Team,

We are getting this error while creating project.

ERROR: Error creating directory file:///mongodb/mongodbweb1/opencga/sessions/ with parents=true

**Comment by pfurio** [comment]
Hi,
Have you checked if the user running OpenCGA have write access in that folder?

**Comment by Mohammedhusen** [comment]
Thank you.
Issues solved by changing the permission on opencga directory.
