### ISSUE TITLE
POST method for modify operations

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#138]
Now, the `{resource}/{id}/modify` operation is using a HTTP GET method. 

In order to be able to modify nested fields like `attributes` or `stats`, a modify using **POST** methods should be implemented.

At this moments, there is a POST method implementation for `users/{id}/modify`

**Comment by imedina** [comment]
As commented in #150 modify must be also renamed to 'update'

**Comment by j-coll** [comment]
Implemented update using POST method for User, Project, Sample and Cohort
