### ISSUE TITLE
opencga builds too long opencga-storage CLIs

### ISSUE THREAD

**Issue by jmmut** [opencb/opencga#147]
It finally happened:
`java.io.IOException: Cannot run program \"opencga/bin/opencga-storage.sh\": error=7, Argument list too long`
This happened because of trying to do stats on a cohort of 17K samples.

Proposals to pass the cohorts from opencga to opencga-storage:
- via file, like `--cohorts-file <path>`
  - contra: we lose jcommander's list parsing
  - contra: another file management needed
- via standard input
  - contra: we lose jcommander's list parsing
  - contra: handling no cohorts?
  - contra: the code would be less homogeneous, as all the other data is passed as input files.

I don't know if there are more options but using a file seems OK.

**Comment by imedina** [comment]
This potential problem was known and two alternatives were implemented to bypass it:
* via StudyConfiguration file, this JSON file is read by opencga-storage CLI. OpenCGA and other tools using opesncga-storage can write this JSON file and pass it as argument.
* via StudyConfigurationManager, this class can be passed using DI and will be used by opencga-storage to get the information needed from the master application such as samples.

j-coll will give more information about this.
