### ISSUE TITLE
Index status is 'NONE' after index an Alignment file

### ISSUE THREAD

**Issue by frasator** [opencb/opencga#149]
Inside the file model, the key index contains information about index status.
After index process the status is NONE :
```javascript
"index" : {
        "userId" : "demo",
        "date" : "20150605142736",
        "status" : "NONE",
        "jobId" : 13181,
        "attributes" : {
            "chunkSize" : 200,
            "indexJobId" : 13181
        }
    },
```
When using fetch web service it returns an error, it says that the file is not indexed.
The index files are created correctly (file system and database) and seems that the index was run with no errors.
Replacing NONE by READY directly on the database did the trick, and the fetch WS started to work.
Seems that the status is not being updated correctly.

**Comment by roalva1** [comment]
Solved in commit https://github.com/opencb/opencga/commit/f4e3b7b03866d71a9d7cda153648f815b830c1c7
