### ISSUE TITLE
_id field shows junk values in variants collection

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1499]
HI Team,

We found that some records have junk values as below in _id field in variants collection.

 1:     83831:PHh��>��������q���;����֡}!��b:*

Will this cause issues in query variants data ?

Actual values are:

"_id" : " 1:     83831:PHh��>��������q���;����֡\u001b}!��b:*",
    "chromosome" : "1",
    "start" : 83831,
    "end" : 83974,
    "length" : 144,
    "reference" : "GAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAGAGAAAGAAAGAAAGAAGAAAGAGAAAGAAAGAAAGAAAGAGAGAGAGAAAGAGAGAGAAAGAAAAAGAAGGAAAGAAAGAAAGAAAGAAAAAAGAAAGAA",
    "alternate" : "*", 

Appreciate your response on this issues.

**Comment by Mohammedhusen** [comment]
Hi Team,

Could you please update on this issues.

Records which has this junk characters we are not able to query from opencga and iva application and this is huge concerned for user who all are looking filter by  chromosome and position.

**Comment by imedina** [comment]
This looks correct. Filed __id_ is an internal id and is binary encoded for different reasons. This should not affect any user since OPenCGA has always handled this internally. Users are expected to user REST API and OpenCGA will query correctly variants.

**Comment by Mohammedhusen** [comment]
Thanks a lot for clarification on this.
