### ISSUE TITLE
solr configuration with opencga

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1511]
Hi Team,

We need your help to configure opencga with solr to speed up query, however we have added solr details into opencga configuration files both catalog and storage, so is there any other steps to be done this to work fine?

If yes could you please share the steps.

Is there way to check that opencga is using solr once it's configured ?

Thanks a lot for support !!

**Comment by Mohammedhusen** [comment]
Team Any update on this ,please .

**Comment by j-coll** [comment]
Hi @Mohammedhusen ,

You first have to configure the Solr in the storage-configuration.yml file. Then, you have to run the "secondary index" on solr. This secondary index should be updated every time that new files are loaded.

I assume that you are using opencga 1.4.x. In that case, you should run this command in the server site:

```
bin/opencga-analysis.sh variant secondary-index --project <PROJECT>
```
The process creates a collection in Solr. You'll need to run one process for each project in your installation.

This can be done automatically when indexing a file adding the flag `--index-search`

**Comment by Mohammedhusen** [comment]
Dear j-coll,

Thanks a lot for your help on this ,now it's working as expected.
