### ISSUE TITLE
How to add custom population frequency in openCGA and IVA

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#1563]
Hi Team,

Is it possible  to have custom population frequency field in opencga and it should be show IVA.

Currently in IVA it is showing 1000 genome and genomad frequency values  .

If yes please share the steps.

Thank you.

**Comment by imedina** [comment]
OpenCGA annotates population frequencies from several studies: ExAC, gnomAD, 1000 Genomes, UK10K, GONL, ...  All of them are available in OpenCGA after variant annotation. You can add them to IVA in main IVA config.js file:

https://github.com/opencb/iva/blob/develop/src/conf/config.js#L449

If you want to annotate with some custom population frequencies you have to add them first to CellBase Variant. Then, when you execute the OpenCGA Variant annotation they will be annotated. Does this make sense?

**Comment by Mohammedhusen** [comment]
Thank you !!
