### ISSUE TITLE
Storage annotator: Population frequencies

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#159]
Cellbase contain calculated population frequencies from reference projects like 1000genomes or EVS. This population frequencies can be very useful to make filter queries over the indexed variants.

Population Frequencies need to be added to the opencga-storage annotation, and implemented the required filter queries.

**Comment by roalva1** [comment]
This feature is necessary for webapps that are using the indexing module. I was said that this week will be done by the cellbase team. The main class to edit is https://github.com/opencb/opencga/blob/develop/opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/DBObjectToVariantAnnotationConverter.java

**Comment by roalva1** [comment]
Hi, 

is there any new information about this feature or due date?

**Comment by javild** [comment]
Already implemented, Testing lacking.

Hopefully will be ready today
