### ISSUE TITLE
Check better when a variant is already in Mongo

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#16]
When multiple instances of OpenCGA's variants loading tool are processing the same chromosome from different studies at the same time, inconsistencies may arise. This is probably due to checking only once whether a variant has been already saved. This condition should be checked not only at the beginning of the DBObject generation, but again right before the insertion.

**Comment by j-coll** [comment]
The loading process now uses [**$setOnInsert**](http://docs.mongodb.org/manual/reference/operator/update/setOnInsert/) to check if a variant is already loaded, so the responsibility relies on MongoBD.

```
db.variants.update( { "_id" : "22_31234_A_C"  }, 
    { 
        {  
            $push : {  
                "files" : { <file-object> } 
             }
        },
        {  
            $setOnInsert : { 
                "_id" : "22_31234_A_C", 
                "chr" : "22", 
                "start" : 31234, 
                "files" : [ ] ,
                <other-fields>
            } 
        }
    }
)
```
