### ISSUE TITLE
Delete methods in OpenCGA-Storage for Variants

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#160]
Currently, the only possible way of delete indexed data was connecting directly to the underlying database. New methods needs to be implemented to delete or "de-index"  variants data.

New methods will be added to the `VariatnDBAdaptor`:

 * `deleteStudy (int studyId, QueryOptions query)`
 * `deleteSamples (List sampleIds, int studyId, QueryOptions query) `
 * `deleteStats (List cohortIds, int studyId)`
 * `deleteAnnotation (int studyId, QueryOptions query)`

The QueryOptions param will be used to delete the data from the matched variants.

**Comment by imedina** [comment]
I think the last methods should be:
 * deleteAnnotation (ID annotId, int studyId, QueryOptions query): more than one annotation can exist

Also, to make deleteStats and deleteAnnotation API more consistent maybe both of them should accept a single ID:
 * deleteStats (int cohortId, int studyId)
 * deleteAnnotation (ID annotId, int studyId, QueryOptions query)

comments?

**Comment by j-coll** [comment]
At this moment, there are no different annotations per variant, so I didn't take in mind the `annotationId` for this issue. We can add this parameter to avoid change the interface in the future.

If you are talking about having both methods (with a single ID, and with a list) for `deleteStats`, I would like, but have only the "single id" version can be constraint.

**Comment by imedina** [comment]
Correct, the main goal of adding annotId is for not changing the API in the future.

Regarding deleteStats, in practice I think the most common use case will be to delete a single stats, or maybe all of them:
 * deleteStats (int studyId): deletes all the stats
 * deleteStats (int cohortId, int studyId): delete one specific stats

I think this good enough for this API level, we can in the future evaluate if a List is needed. Also, think that the CLI or REST web services can accept a List of statsId and the call to StorageEngine API several times.

**Comment by imedina** [comment]
Mostly done, only _deleteSamples_ method has been delayed to v0.7 since it was not needed for this release.
