### ISSUE TITLE
aggregated stats are not loaded when the variant is already present 

### ISSUE THREAD

**Issue by jmmut** [opencb/opencga#161]
the stats are written if the setOnInsert is used, because the converter handles it, but otherwise, only an source entry is added, see https://github.com/opencb/opencga/blob/hotfix/0.5/opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBWriter.java#L265

**Comment by imedina** [comment]
This was fixed long time ago. Thanks.
