### ISSUE TITLE
Allow stats from aggregated files to be calculated in post-load stage

### ISSUE THREAD

**Issue by jmmut** [opencb/opencga#163]
to make this possible we have to:

* separate aggregated stats from [VariantAggregatedFactory](https://github.com/opencb/biodata/blob/develop/biodata-models/src/main/java/org/opencb/biodata/models/variant/VariantAggregatedVcfFactory.java) in another module, maybe biodata-tools.
* allow using this new module during transform and during postload.
* during postload, the data to compute stats must be read from DB, as non-aggregated stats are done.
* make sure the stats can be parsed or inferred from attributes (or source line) present in the DB. This includes revising that we are storing everything needed in the attributes.

**Comment by imedina** [comment]
This is a very interesting and needed feature. I would add that the new refactoring and implementation is MapReduce/Spark friendly.
