### ISSUE TITLE
Read-Write operations for VariantDBAdaptor

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#164]
Originally, `VariantDBAdaptor` was designed to be a read-only database connection, and the writing was made by the `VariantDBWriter`.

By implementing methods like `updateStats` and `updateAnnotation`, this rule was broken. The centralization of database operations in a single interface results easier to be implemented by the different storage engines, and easier for doing unit tests.

So, will be needed to add the remaining write operations to the `VariantDBAdaptor`, and make the `VariantDBWriter` to use it. The new methods will be:

 * `+ insertVariants( data : List<Variants>, sc : StudyConfiguration) : QueryResult`
 * `+ ensureIndexes( options : QueryOptions) : QueryResult`

**Comment by imedina** [comment]
I totally agree with this, XxxDBAdaptors must centralize all DB operations. Just a few comments about method API:
 * insert( data : List<Variants>, sc : StudyConfiguration): adding the suffix 'Variants' is redundant since we are in VariantDBAdaptor.
 * createIndex( options : QueryOptions): 'ensure' nomenclature is too MongoDB related, even them have deprecated that method and favour 'create' which is more standard. Also, creating index can be a very expensive operation, a single index must be created at this level in each call.

A new method should be added:
 * insert( data : List<Variants>, int studyId, ...): a API with basic types (int, String, ...) must exist, methods with StudyConfiguration objects must call to 'basic' API

comments?

**Comment by cyenyxe** [comment]
I would keep two different interfaces, one for reading and one for writing. They are clearly two different tasks, and putting all together would derive into a single complex component instead of two simpler ones. Plugin developers could still implement them in the same class if they want.

**Comment by j-coll** [comment]
As I see, the main task is the communication with the DataBase.
I think that the idea of having a centralized API in the VariantDBAdaptor will not necessary derive into a complex component. Plugins can implement it through a facade pattern if the implementation is too complex.

About the `createIndex`, maybe it does not have to be added to the `VariantDBAdaptor` general interface. Create indexes is a very common operation in small DDBB, but not so common in BigData. It would be a method only into the `VariantMongoDBAdaptor`, called in the `postLoad()` of the indexation.

**Comment by cyenyxe** [comment]
When you mention "communication with the database" are you referring to the "open" or "pre" methods? Talking specifically about those, the concept of mixing methods such "pre" and "post" with "getAllVariants" in the same interface looks weird to me.

Also, the VariantDBAdaptor class is already 1k lines long and VariantDBWriter is 400. Even after removing some deprecated contents from VariantDBWriter, are you sure you want to put them together?

In terms of "code usability", some snippets below.

Having two interfaces and one class:
<pre>
interface VariantDBAdaptor
interface VariantDBWriter
class MongoDBManager implements VariantDBAdaptor, VariantDBWriter
</pre>

Two interfaces and two classes:
<pre>
interface VariantDBAdaptor
interface VariantDBWriter
class MongoDBAdaptor implements VariantDBAdaptor
class MongoDBWriter implements VariantDBWriter
</pre>

One interface and one class:
<pre>
interface VariantDBAdaptor
class MongoDBAdaptor implements VariantDBAdaptor
</pre>

One interface and two classes:
<pre>
interface VariantDBAdaptor
class MongoDBAdaptor implements VariantDBAdaptor
class MongoWriter (MongoDBAdaptor calls for writing)
class MongoReader (MongoDBAdaptor calls for reading)
</pre>

So having two interfaces is equally easy to use, but gives more flexibility at no cost. The other gives the option of using one class or having to deal with "glue" layers.

**Comment by j-coll** [comment]
The communication with the DB, will be all CRUD operations over the database. At this moment, we have READ and UPDATE operations. In the ticket #160 we are discussing about having DELETE methods. This issue was about moving the CREATE methods to the DBAdaptor. Methods `pre()` and `post()` are exclusively from the `DataWriters`. The only one that makes sense here is the `close()` method.
