### ISSUE TITLE
Example file for settings.xml

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#165]
OpenCGA can be compiled directly, just by  executing `mvn install -DskipTests`, but some configuration files can be customized with the content of the file `~/.m2/settings.xml`

This file is not needed for the installation, but makes easier for developers to compile, install and configure at the same time the program, by **[filtering](http://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html)** the resources files. Also, this information is used to run the tests. In that case, this file is required.

Will be very useful to have a template `settings.xml` file with all the configurable properties. At this point, it's only possible to know which are these properties by reading the different config files.
An example file could make this configuration step easier.

**Comment by imedina** [comment]
In CellBase README we have an example of the Maven profile:

https://github.com/opencb/cellbase#build

**Comment by jmmut** [comment]
basic example done in https://github.com/opencb/opencga/wiki/Download-and-Installation

**Comment by imedina** [comment]
According to http://stackoverflow.com/questions/10381005/what-is-the-order-of-overwrite-maven-properties-in-pom-xml-and-settings-xml and http://maven.apache.org/settings.html#Profiles profiles from settings.xml will overwrite pom.xml. And this include the properties. After some checks I have confirmed this.
Then, to improve user experience a 'default-config' functional profile should be created in main pom.xml. Developers and advanced users can define a profile in settings.xml as needed.
