### ISSUE TITLE
Annotation Sets for Files

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#167]
`AnnotationSets` are a very useful idea for annotate samples with user defined `VariableSets`, which acts like a form. [Read more](https://github.com/opencb/opencga/wiki/OpenCGA-Catalog#sample-annotation)

This useful mechanism was designed to annotate samples, and only samples, but maybe this constraint is not really needed. 

It would be a very interesting feature to extend this it mechanism to annotate File entries.

**Comment by imedina** [comment]
This functionality can be partially obtained with File attributes, not sure if this is needed.

**Comment by imedina** [comment]
This was finally not needed, closing this old issue
