### ISSUE TITLE
Job deletion doesn't work

### ISSUE THREAD

**Issue by mwhamgenomics** [opencb/opencga#1688]
I'm getting 'null' errors when I try to cancel jobs. For example:

```
$ opencga.sh variant stats-run <args...>
#ID	TOOL_ID	CREATION_DATE	STATUS	WARNS	ERRORS	INPUT	OUTPUT	OUTPUT_DIRECTORY
variant-stats.20201204141518.WjdaZw	variant-stats	20201204141518	PENDING	-	-	-	-	-
$ opencga.sh jobs search
#ID	TOOL_ID	CREATION_DATE	STATUS	WARNS	ERRORS	INPUT	OUTPUT	OUTPUT_DIRECTORY
variant-stats.20201204141518.WjdaZw	variant-stats	20201204141518	PENDING	-	-	-	-	-
$ opencga.sh jobs delete --job  variant-stats.20201204141518.WjdaZw
ERROR 0: null
```

This means that if I need to re-submit a job for whatever reason, I can't cancel the old pending one.

**Comment by pfurio** [comment]
Hi @mwhamgenomics,

Thanks for reporting the issue. I fixed the fact that jobs could not be deleted. However, although this will be fixed, /delete will only be able to delete already finished or failed jobs. What you want is a different action which we have planned for next release 2.1.0. We still don't know if it will be called "abort", "kill" or something else  but you will be able to do so in the next couple of months.
