### ISSUE TITLE
IVA aggregation tool per consequence type: shows a table with unformatted names

### ISSUE THREAD

**Issue by lauralopezreal** [opencb/opencga#1712]
OpenCGA Aggregations seems to return weird SO accessions when trying to aggregate per consequence type;  for instance see the following picture:
![image](https://user-images.githubusercontent.com/60696900/109020398-d5038a00-76b1-11eb-8c22-4ef89372b35d.png)

It would be great to get the SO names instead of the accessions, for more clarity of the users.

**Comment by imedina** [comment]
Thanks @lauralopezreal !

This has been already fixed :-)

![image](https://user-images.githubusercontent.com/1427327/109239968-74b63a80-77ce-11eb-808b-887612c5248c.png)
