### ISSUE TITLE
Missing affectationStatus from Individual

### ISSUE THREAD

**Issue by mwhamgenomics** [opencb/opencga#1781]
When I try to update an Individual with the field `affectationStatus` (which I think is meant to be the phenotype column in a Ped file?), nothing happens:

```python
>>> r = client.individuals.update('indv_id', {"affectationStatus": 'AFFECTED'})
>>> r.response
[{'time': 0, 'events': [{'type': 'ERROR', 'code': 0, 'id': 'indv_id', 'message': 'Could not update individual indv_id: Nothing to be updated'}], 'numResults': 0, 'results': [], 'resultType': '', 'numTotalResults': 0, 'numMatches': 0, 'numInserted': 0, 'numUpdated': 0, 'numDeleted': 0, 'attributes': {}, 'result': []}]
```

The Rest API log shows a CatalogDBException('Nothing to be updated'), and the message `ERROR IndividualMongoDBAdaptor:384 - Non-processed update parameters: [affectationStatus]`. Looking into the source of this in IndividualMongoDBAdaptor, I can see handling for other parameters like UID, disorders, phenotypes, etc. (and entries for them in IndividualDBAdaptor.QueryParams), but nothing for affectation status.

I tried adding the status directly in the catalog database:
```
mongodb> db.individual.updateOne({'name': 'indv_id'}, {'$set': {'affectationStatus': 'AFFECTED'}})
{ "acknowledged" : true, "matchedCount" : 1, "modifiedCount" : 1 }
```

But it still didn't show up, which makes me think the field's also not being returned properly in GET requests:
```
>>> client.individuals.search(name='indv_id').response
[{'time': 22, 'events': [], ...}]  # affectationStatus not present in response
```

**Comment by mwhamgenomics** [comment]
Spoke to @imedina and @lauralopezreal on Monday and discussed it:

- Since a single Study could be used to look at multiple diseases, affectationStatus is being removed in favour of Disorders and Phenotypes
- A Phenotype describes a single clinical feature/symptom, e.g. coughing
- A Disorder describes a disease, e.g. asthma
  - This is what gets used as the affected/unaffected status in a case interpretation
  - A case interpretation is for a single Disorder
- Disorders and Phenotypes have an ID (HPO/OMIM term), a source (e.g. HPO, OMIM) and a descriptive name
  - For now this is freeform, but could be integrated/validated in the future

Based on the above, I think this issue should instead be for explicitly deprecating affectationStatus in the front-facing API

**Comment by pfurio** [comment]
Thanks for our input @mwhamgenomics.  This field was deprecated and removed time ago from the main Individual data model but it was clearly not properly removed from the list of fields that can be updated. I will remove that now.
