### ISSUE TITLE
Return updated or inserted object in response to avoid extra request

### ISSUE THREAD

**Issue by Rodielm** [opencb/opencga#1840]
## Description

At this point the sample, individual, family and cohort "endpoint" creating or updating information returns a 0 or 1.
This forces us to request an extra service to update information for IVA 

Example:

![image](https://user-images.githubusercontent.com/10471758/141289148-109fdfbf-044a-4509-9690-8c3c496ee18e.png)

`numMatches: means the record/data has the same information`
`numInserted: means the record/data  has been inserted`
`numUpdated: means the record/data has been updated`
`numDeleted:  means the record/data has been deleted`
  
## Expected behavior

Once the data has been saved on the server, the server must return the information it has saved to update our copy in IVA without having to request an extra service.

## Solution
After the server saves the information, it must return it.

Ex.
- Insertion & Update: Must be the same information on both sides.

**Comment by pfurio** [comment]
We will be adding a new query parameter field `includeResult` to all `/update` and `/create` web services. By setting this flag to true, the server will perform an additional query to the database to fetch the recently updated or created document.

**Comment by imedina** [comment]
Maybe `inlcudeObject` is a better name than `includeResult`?

**Comment by pfurio** [comment]
As much as I love naming discussions, I'd say `includeResult` is a better name in this case. Our actual OpenCGA response object has a list of `results` filled with the actual results. Also, we have a `numResults` field containing the size of the array of `results`  returned. So to be consistent with those already existing fields, I would definitely name it `includeResult` to avoid possible confussions.
