### ISSUE TITLE
getAllVariantsByRegionAndStudies returns incorrect value

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#19]
getAllVariantsByRegionAndStudies should return `QueryResult<Variant>`. Now the function returns `QueryResult<DBObject>`

https://github.com/opencb/opencga/blob/develop/opencga-storage/src/main/java/org/opencb/opencga/storage/variant/mongodb/VariantMongoDBAdaptor.java#L74-L89

**Comment by imedina** [comment]
VariantDBAdaptor API has been redesigned, and reimplemented in v0.6 for MongoDB, this issue is fixed in this new version.
