### ISSUE TITLE
Accept AND or OR operations on the VariantFilters

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#204]
At this moment, for querying variants, most of the variant filters implement an OR operation between all the elements of the filter. Although, this is not true in some filters.

The rule will be to use `,` as OR and `;` as AND.
Is required a formalization of this decision, check if there is any query that doesn't follow this rule and implement the AND operation in most of the filters.

At this first implementation, every filter will accept *only one type of operations*

Examples:
 * `study = ph1,ph3`  -> Variants present in studies Phase1 OR Phase3 (union)
 * `study = ph1;ph3`  -> Variants present in studies Phase1 AND Phase3 (intersect)
 * `study = ph1;!ph3`  -> Variants present in study Phase1 AND NOT in Phase3 (complement)

**Comment by imedina** [comment]
Nice, just to summarize:

1. not all parameters will accept `;`, for instance region or gene lists are always ORs
2. it is not allowed to mix `,` and `;` at this moment
3. if only ANDs are used then we can make the negation with `!`
