### ISSUE TITLE
CatalogManagerException should be renamed

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#21]
CatalogManagerException should be renamed to CatalogDBException to reflect properly that the exception comes from the database

**Comment by j-coll** [comment]
Now the main exception is [CatalogException](https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/CatalogException.java), witch has two inheritance exceptions: [CatalogIOManagerException](https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/io/CatalogIOManagerException.java) and [CatalogDBException](https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/CatalogDBException.java)
