### ISSUE TITLE
Create, Delete and Modify user groups

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#217]
Currently, existing groups are harcoded, and can not be created, modified (except from adding or removing users) or deleted.

Will be a desired feature to be able to create, delete and modify existing groups.

- [ ] Create new groups
- [x] Update groups: Add and remove users from a group.
- [ ] Delete groups
- [ ] Propagate changes to the web services
- [ ] Document the new functionality in [Authorization - Groups](https://github.com/opencb/opencga/wiki/Authorization#groups)

**Comment by pfurio** [comment]
The way to manage groups has changed in version 0.8 and it is already implemented.
