### ISSUE TITLE
Implement GA4GH REST variant methods

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#226]
GA4GH methods including beacon should be implemented, this will return GA4GH data models so a OpenCB Variant to Ga4GH Variant may be needed. More info at http://ga4gh.org/#/api/v0.5.1

**Comment by cyenyxe** [comment]
Those converters had already been implemented, to a certain extent: https://github.com/opencb/biodata/tree/develop/biodata-models/src/main/java/org/opencb/biodata/models/variant/ga4gh

The last changes to the models may need to be included, though.

**Comment by j-coll** [comment]
The ga4gh models are now read from [opencb/ga4gh](https://github.com/opencb/ga4gh) repository, as they are not part of biodata models. 
Biodata [ga4gh converters](https://github.com/opencb/biodata/tree/develop/biodata-tools/src/main/java/org/opencb/biodata/tools/variant/converter/ga4gh) converters has been updated to use the new models.

Using the converters, a new endpoint has been created:
`/opencga/webservices/{version}/ga4gh/variants/search`
Returning the ga4gh models v0.5.1.

Also, any other webservice that fetch variants (`studies/{sid}/variants` or `files/{fid}/variants`) can return variants in ga4gh model adding `model=ga4gh` to the URL.
