### ISSUE TITLE
Access Control Lists for Individuals

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#239]
Resources with ACLs are Files and Samples.

To determine the user permission over an individual, group permissions and sample ACLs are read. A user can read to an individual if:
 * User is SAMPLE_MANAGER, role:ADMIN or studyOwner
 * User can read some related sample

Any other permission require to be SAMPLE_MANAGER, role:ADMIN or studyOwner

In order to allow more accurate authorization management, Individuals should have also ACLs.

**Comment by pfurio** [comment]
This has been solved and not only files, samples and individuals have now ACLs, but also cohorts, jobs, datasets, disease panels and studies. The complete list of ACLs defined for these resources can be seen in the [link](https://github.com/opencb/opencga/tree/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/acls)
