### ISSUE TITLE
General interfaces for Catalog models with shared features

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#240]
There is a set of features that are shared by a certain number of Catalog models. Some actions are performed over all the featured objects, like manage ACLs, or annotations.

An incomplete list of this shared features could be:
 * Can be annotated
 * Contains ACLs
 * Contains id, name and alias
 
This interfaces will help to reuse more code in some cases.

**Comment by pfurio** [comment]
This was done months ago. We have now an Annotable class that will be extended by the models using annotations (Sample, Cohort and individual in this moment). The class can be found [here](https://github.com/opencb/opencga/blob/release-0.8.0/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/Annotable.java). 

Something similar was done for the ACL class,  the class can be found [here](https://github.com/opencb/opencga/blob/release-0.8.0/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/acls/permissions/AbstractAclEntry.java).
