### ISSUE TITLE
Edit VariableSets

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#241]
Variables allow users to add annotation to certain objects in catalog.

Since #191 is finished, we can easily update the annotation, but always with the same variables. An small set of operations over VariableSets should be implemented to allow some flexibility on this annotations.

The required operations are:
 * Add new **non required** Variables
 * Remove Variables. Will remove all the existing annotations for these variables
 * Rename Variables. Will modify all the existing annotations for these variables

**Comment by j-coll** [comment]
In the future, more operations should be added, like:
 * Add and remove allowed values to categorical variables
 * Change the type of a variable
 * Change the requirement of a variable (both directions)
 * Add **required** variables with default value

**Comment by pfurio** [comment]
This is already implemented. Now, it is possible adding, modifying and deleting new variables to an existing and already annotated variableSet. 
Changing the type of variable is not supported. However, the behaviour could be achieved following these steps:

1. Adding a new variable with the desired type.
2. Update the annotations using the old annotation of the variable to be removed.
3. Remove the variable no longer needed.
