### ISSUE TITLE
Implement a benchmark framework for OpenCGA Storage

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#248]
In order to improve development and test different systems and configurations a benchmark framework should be developed in OpenCGA Storage.

**Comment by jtarraga** [comment]
New commits about this issue:

- 1c6c7fb6f3c5018ad4a02ec4059505252ef72a4d: storage: add more query generators (for conservation, protein subst. and functional scores; and for biotypes, types, studies,...)

- 44977a9c5af61c5d1b19f5bfe0c1df30cb1ff46f: Merge branch 'feature-jmeter' of https://github.com/opencb/opencga into feature-jmeter

- 8d58f89beed47b71bdd9687fd6e1ab7a8ed92468: storage: fix checkstyle
