### ISSUE TITLE
Code cleaning in opencga-server/src/main/webapp/webservices/swagger-ui/lib/shred.bundle.js

### ISSUE THREAD

**Issue by jcortell** [opencb/opencga#279]
Lint Warning line 1
Redefinition of 'require'.

Lint Warning lines 9, 120,  143,  199,  200, 203,  385,  408, 438, 443,  491, 504, 539, 552, 554, 570,  574, 576,  596, 600, 602, 637, 643, 644, 650, 653,  657, 667, 673, 676, 680,  694, 715, 723, 731, 741, 742,  744, 748, 749, 757, 765, 939, 900, 1024, 1029, 1030, 1033,  1272
Missing semicolon.

Lint Warning lines 33, 648, 649
Bad line breaking before '||'.

Lint Warning lines 64, 68, and 86
'm' is already defined.

Lint Warning lines 138, 256, 622, 627, 632, 755
Bad line breaking before '?'.

Lint Warning line 172
Bad line breaking before '&&'.

Lint Warning lines 352, 353, 412, 515, 516, 605, 606, 607, 6013, 614, 773, 774, 775, 776, 777, 778, 779
Bad line breaking before ','.

Lint Info line 353
Comma warnings can be turned off with 'laxcomma'.

Complexity lines 446 - 49112 code paths in this function

Lint Warning line 448
'options' is already defined.

Lint Warning lines 483, 487
Expected a 'break' statement before 'case'.

Complexity lines 603 - 64411 code paths in this function

Lint Warning line 615
Expected an assignment or function call and instead there is an expression.

Lint Error line 637
Line breaking error 'break'.

Complexity lines 655 - 6769 code paths in this function    

Lint Warning lines 699, 713, 900, 902, 916
Did you mean to return a conditional instead of an assignment?

Lint Warning line 901
Expected a 'break' statement before 'default'.

Lint Warning lines 992 and 1322
Unnecessary semicolon.

Complexity lines 1067 - 113018 code paths in this function

Lint Warning line 1072
Missing '()' invoking a constructor.

Lint Warning line 1201
Bad line breaking before '+'.

Duplicate lines 1849 - 1859
11 lines duplicated in this file.

Duplicate lines 1936 - 1940
lines duplicated in opencga-server/src/main/webapp/webservices/swagger-ui/lib/shred/content.js 
on lines 
- 14-18
- 37-49
- 50-53
- 64-70
- 71-75
- 91-95
- 105-119
- 126-131 
- 144-156

**Comment by imedina** [comment]
First, thanks for reporting this but I'm afraid this has noting to do with OpenCGA. We use Swagger project (http://swagger.io/) to provide the REST WS documentation, to do this you need to copy Swagger code and that is what we did, so all these issues you have find should be reported to Swagger since it is not our code. Thanks anyway!
