### ISSUE TITLE
Implement a way to define groups and permissions in a simple way

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#290]
At the moment, the user cannot define new groups at other level rather than study. We should be more flexible and allow them to create group permissions easier.

**Comment by j-coll** [comment]
Related with: #217

**Comment by pfurio** [comment]
A new way to manage users, groups, roles and permissions have been defined. The implementation is already done. Still lacking the documentation.

- [ ] Create the documentation to work with the new kind of permissions.
