### ISSUE TITLE
Server UploadFile concatenate and finish uploading process.

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#30]
Concatenation of __partial_ files should be done by the daemon (or, in the future, by the workers).

When _lastChunk_ arrive, **file.status** should change from "uploading" to "uploaded".
Then, the daemon should concatenate, calculate checksum, move to the final destination and, then, set **status** to "ready".

**Comment by imedina** [comment]
Chunk-based upload web services has been deprecated and will be removed, closing this issue
