### ISSUE TITLE
Export variant statistics

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#309]
Statistics for cohorts (populations, families, ...) are now calculated and loaded in OpenCGA-Storage to allow queries filtering with those values.

It may be interesting to be able to export these values to a file, using different formats like _aggregated vcf_, _tsv_ or _json_
- [x] Aggregated VCF stats
  - [x] Don't return samples information
- [x] TSV with stats per cohort
- [x] Population Frequencies

**Comment by j-coll** [comment]
Variant frequencies can be exported executing:

`opencga-analysis.sh variant export-frequencies -s <study> --output-format <vcf|tsv|cellbase|json>`

**Comment by imedina** [comment]
This must be documented in new Confluence documentation site, moving this to RC3
