### ISSUE TITLE
Remove variant-lib repository dependency

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#31]
OpenCGA depends on variant-lib for the VariantRunner. This variant-lib repository is going to be removed so this dependency must be removed.
Current variant-lib in code in use must be either taken to biodata or to OpenCGA

**Comment by cyenyxe** [comment]
Fixed in 07abe86cbfd2a194118fef39bf6772a79bc0951a, the code mentioned above has been moved to the module biodata-tools inside the Biodata repository.
