### ISSUE TITLE
Speed up VariantMongoDBWriter

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#32]
Use Bulk Operations and threads in order to speed up the load variants operation.

**Comment by imedina** [comment]
By modifying the batchSize and using a multi-thread approach we have achieved a 3x speed-up in MongoDB. This should improve quite a lot with MongoDB WiredTiger storage engine.
New available snappy compression must be tested. But we re close to close this ticket.

**Comment by imedina** [comment]
This has been successfully done.
