### ISSUE TITLE
Accept multiple rs/ss IDs in a single variant

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#34]
Stored variants must accept multiple rs/ss IDs instead of just one, as it currently happens.

**Comment by imedina** [comment]
Where all these multiple IDs come from? VCF files? They should be stored in 'annotation.xrefs'

**Comment by cyenyxe** [comment]
Yes, they will come from multiple VCF files. Right now the read value is saved only the first time the variant is found, and stored in an "id" field in the root of the document.

It is fine if we save it in the "annotation" field, but it will be overwritten every time the annotations are loaded, won't it?

**Comment by j-coll** [comment]
Multiple IDs are stored as an array in the mongoDB collection. New IDs are added (_$addToSet_) to this array.  

**annotation.xrefs** will contain only information provided by the annotator tool.
