### ISSUE TITLE
Missing dependency for develop branch

### ISSUE THREAD

**Issue by abhi-mshetti** [opencb/opencga#349]
I tried working with 'develop' branch and was stuck at one point where maven was trying to find a non-existent dependency.

It worked only after I manually installed [hpg-bigdata](https://github.com/opencb/hpg-bigdata). Maybe this should be part of the documentation?

**Comment by pfurio** [comment]
Thanks for letting us know. Yes, we now have a new dependency on [hpg-bigdata](https://github.com/opencb/hpg-bigdata) like you mentioned. I will put that in the documentation.
