### ISSUE TITLE
Can only specify option --include-genotypes once.

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#355]
This error was found using the master branch as of August 30th, 2016

Following the instructions for Indexing variants on this page:

https://github.com/opencb/opencga/wiki/Indexing-Variant-Data

I get an error running the following command:

`./opencga.sh files index -u myuser -p mypass -id myuser@myproject/mystudy/ALL.chr22.phase1.projectConsensus.genotypes.vcf.gz  -- --include-genotypes --compress-genotypes --calculate-stats`

The error message reads:

> Can only specify option --include-genotypes once.

It appears the above command subsequently executes a series of commands, one of which shows up as:

> /home/philip/opencb/opencga/build/bin/opencga-storage.sh index-variants  --storage-engine mongodb --file-id 6 --study-name 'philipwu@myproject:mystudy' --study-id 2 --database opencga_philipwu_myproject --input file:/opt/opencga/sessions/users/philipwu/projects/1/2/ALL.chr22.phase1.projectConsensus.genotypes.vcf.gz --outdir file:///opt/opencga/sessions/jobs/I_4vBEte2aqw/ --include-genotypes  --log-level info --include-genotypes --compress-genotypes --calculate-stats

As you can see the flag for --include-genotypes shows up twice in the command causing the failure.

**Comment by j-coll** [comment]
The problem is with the tutorial you are reading. It is for the version 0.6.0.

I will update the tutorials to specify the version that they refer.

**Comment by j-coll** [comment]
Please, see the updated tutorial:
[Indexing Variant Data v0.7.0](https://github.com/opencb/opencga/wiki/Indexing-Variant-Data-v0.7.0)

Reopen this issue if you have any problem
