### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.opencb.opencga.server.ws.UserWSServer

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#356]
Using the master branch RESTful API deployed on Tomcat 8, I get the following error when trying to use the following endpoint:

/{version}/users/{userId}/login

`A MultiException has 2 exceptions.  They are:
1. java.lang.NoClassDefFoundError: Could not initialize class org.opencb.opencga.server.ws.UserWSServer
2. java.lang.IllegalStateException: Unable to perform operation: create on org.opencb.opencga.server.ws.UserWSServer

	org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:394)
	org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:470)
	org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:162)
	org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2065)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:761)
	org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:700)
	org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:169)
	org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:185)
	org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:74)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:109)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:112)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:92)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:61)
	org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:300)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)`

**Comment by j-coll** [comment]
I can imagine that the tomcat server did not start properly. Can you search in the tomcat log file `tomcat/logs/catalina.out` for a message like this one?

```
 ========================================================================
 | Starting OpenCGA-server, creating OpenCGAWSServer
 | This log must appear only once.
 |  * OpenCGA home set to: /home/jcoll/opt/opencga/
 |  * Server logfile: /home/jcoll/opt/opencga/logs/server.log
 |  * Reading StorageConfiguration
 |  * Initializing StorageManagerFactory
 |  * Initializing CatalogManager
 ========================================================================
```

**Comment by Philip-Wu** [comment]
Thanks @j-coll 

You're right, those tomcat messages never appear in the log file. But at the same time, no errors are reported. The home page localhost:8080/opencga loads up just fine too.

Can I ask which tomcat version you are currently using?
I may consider trying tomcat7

thanks

**Comment by Philip-Wu** [comment]
Still no dice with tomcat 7, but i did get a different error this time which may help pinpoint the issue. Stack trace below:

`**java.lang.NullPointerException
	org.opencb.opencga.catalog.CatalogManager.configureDBAdaptor(CatalogManager.java:159)**
	org.opencb.opencga.catalog.CatalogManager.<init>(CatalogManager.java:106)
	org.opencb.opencga.server.ws.OpenCGAWSServer.<clinit>(OpenCGAWSServer.java:177)
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1129)`

**Comment by Philip-Wu** [comment]
After debugging the code, it turns out my Properties instance is null. 
How do you guys configure your properties? I suspect i'm missing a configuration file of some sort

Thanks

**Comment by Philip-Wu** [comment]
After further debugging, it seems I'll need a configuration file 

**/opt/opencga/conf/storage-configuration.yml**

do you guys have a template YML file I could use as an example?

thanks

**Comment by Philip-Wu** [comment]
Finally figured it out. Copied the contents of build folder into /opt/opencga and no more errors

thanks
