### ISSUE TITLE
GA4GH RESTful API not working

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#359]
When trying to run a search on the variants using the RESTful API (/{version}/ga4gh/variants/search), I get the following error:

`java.lang.NoSuchMethodError: org.ga4gh.models.Call.setCallSetId(Ljava/lang/String;)V
	org.opencb.biodata.tools.variant.converter.ga4gh.GAVariantFactory.parseCalls(GAVariantFactory.java:134)
	org.opencb.biodata.tools.variant.converter.ga4gh.GAVariantFactory.create(GAVariantFactory.java:66)
	org.opencb.opencga.server.utils.VariantFetcher.convertToGA4GH(VariantFetcher.java:170)
	org.opencb.opencga.server.utils.VariantFetcher.variantsStudy(VariantFetcher.java:162)
	org.opencb.opencga.server.utils.VariantFetcher.variantsStudy(VariantFetcher.java:67)
	org.opencb.opencga.server.ws.Ga4ghWSServer.searchVariants(Ga4ghWSServer.java:99)`

Using the following JSON body:

`{ "variantSetIds": ["2"], "referenceName": 22,"start": 0 ,"end":  17671934, "pageSize": 1}`

It appears that the **GAVariantFactory.class** is provided as library from the biodata toolset, and could be out of step

**Comment by j-coll** [comment]
As I see, there is a discrepancy between the ga4gh dependency in opencga-app and opencga-server.
This will be fixed in the version 0.7.1 and 0.8.0.

We are about to release the new 0.8.0 version in the next weeks, which contains a lot of improvements and fixes. You may find interesting the new version. See branch [release-0.8.0](https://github.com/opencb/opencga/tree/release-0.8.0)

**Comment by j-coll** [comment]
Checkout to the branch [hotfix-0.7](https://github.com/opencb/opencga/compare/hotfix-0.7) to find the changes.

**Comment by Philip-Wu** [comment]
Grabbed hotfix-0.7 and merged with master branch in my local repo using command:

> git merge origin/hotfix-0.7

Built and redeployed to tomcat, and I can confirm the GA4GH API is now working

Thanks @j-coll

**Comment by j-coll** [comment]
Actually, you don't need to merge with the master branch since the hotfix-0.7 branch comes directly from the master
