### ISSUE TITLE
Using the daemon to run VCF import doesn't work for v0.8.0

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#388]
**Version: 0.8.0**

Following the instructions found here: 
https://github.com/opencb/opencga/wiki/Indexing-Variant-Data-v0.8.0

> 2016-09-29 09:19:44 [main] INFO FileManager:202 - Looking for file 6 org.opencb.opencga.analysis.AnalysisExecutionException: Unable to execute index. Outdir '/home/philip/opencb/opencga/sessions/jobs/J_1101' **must be empty!** at org.opencb.opencga.analysis.variant.AbstractFileIndexer.outdirMustBeEmpty(AbstractFileIndexer.java:46) at org.opencb.opencga.analysis.variant.VariantFileIndexer.index(VariantFileIndexer.java:117) at org.opencb.opencga.analysis.variant.VariantFileIndexer.index(VariantFileIndexer.java:97) at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.index(VariantCommandExecutor.java:363) at org.opencb.opencga.app.cli.analysis.VariantCommandExecutor.execute(VariantCommandExecutor.java:118) at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:92) at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:31)

The folder was created by the daemon so it never existed prior to running the command. It added log files to the folder.

**Comment by pfurio** [comment]
Hi Philip. Thanks and apologies for the issue. We have already opened a new branch that will contain any bug fix such as this one called release-1.0.0-rc1.1. This is issue is now fixed there.
