### ISSUE TITLE
REST service: Parameter "count" of operation "individuals/search" has type "boolean" instead of "integer"

### ISSUE THREAD

**Issue by ernesto-ocampo** [opencb/opencga#390]
This parameter should specify the "total number of results".

**Comment by ernesto-ocampo** [comment]
Same in operation jobs/search

**Comment by ernesto-ocampo** [comment]
Same in operation samples/search

**Comment by ernesto-ocampo** [comment]
Same in operation studies/search

**Comment by ernesto-ocampo** [comment]
Same in operation {studyId}/alignments

**Comment by pfurio** [comment]
Thanks for the report.

In fact, that parameter has to be a boolean. It is just to indicate that instead of returning the results themselves, it has to return the number of results matching the query. The parameter description will be updated as well.

**Comment by ernesto-ocampo** [comment]
Oh! my bad!

**Comment by pfurio** [comment]
Just checked everything and it was all correct. They were all booleans.
