### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#396]
Catalog does not link files to which it does not have access to. However, it does return an OK when used via webservices instead of an error:

{
  "apiVersion": "v1",
  "warning": "",
  "error": "",
  "queryOptions": {
  },
  "response": [
    {
      "id": "Link file",
      "time": 0,
      "dbTime": -1,
      "numResults": 0,
      "numTotalResults": 0,
      "warningMsg": "",
      "errorMsg": "File file:\/\/\/test_genomes\/LP2000254-DNA_D03\/RAREP00055\/Metrics\/LP2000254-DNA_D03.GCDistribution.csv does not exist",
      "resultType": "",
      "result": [
      ]
    }
  ]
}

**Comment by Philip-Wu** [comment]
I'm using version 1.0.0-final. How do I go about linking files that already exist on the server using the web services?

thx
