### ISSUE TITLE
"count" flag doesn't work in studies/{studyId}/variants REST API

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#407]
Release: v1.0.0-rc1
REST endpoint: opencga-1.0.0-rc1/webservices/rest/v1/studies/{studyId}/variants

**Comment by j-coll** [comment]
This bug has been already fixed for the rc2 at:

[ 4d839e5 - server: Fix count variants with endpoint {studies|files}/X/variants?count=true](https://github.com/opencb/opencga/commit/4d839e543db6a555e73e09d01a761cef73206f94)
