### ISSUE TITLE
"opencga.sh files copy" puts "null" into study file path if no "--path" specified

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#418]
"**--path**" option in "_opencga.sh files copy_" command is optional and when the parameter is not specified opencga uses "**null**" in "Study file path" and obviously fails to find directory that doesn't (and shouldn't) exist.

E.g.: .../sessions/users/{user}/projects/{id}/{studyId}/**null**/

Release: v1.0.0-rc1

**Comment by pfurio** [comment]
Thanks for ticket. This has been already solved and will be delivered with the next release RC2.1.

**Comment by dnafault** [comment]
Thanks, what was the original bug it was fixed under and in what branch it was fixed ? I see the commit but it was just 1 hour prior the comment.
