### ISSUE TITLE
Create new alignment tools

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#433]
A new alignment manager has been implemented in biodata repository. That manager is able read and iterate over a BAM/SAM file and return the reads using in ReadAlignment avro and proto (from GA4GH) as well as SamRecord formats. Besides, it is able to calculate the coverage and some global alignment stats. Things to be done:
- [x] Create a new alignment storageManager and dbAdaptor in storage that will consume that.
- [x] New GRPC webservice to query the alignments of a BAM using streaming of file.
- [x] New REST webservice to query the alignments of a BAM file.
- [x] New REST webservice to query the stats of a BAM file.
- [x] New REST webservice to query the coverage of a BAM file.
- [x] Create the corresponding command lines to query the new GRPC and REST alignment webservices.

Create a default implementation with:

- [x] New layer of iterators over the alignments.
- [x] New method that will retrieve the stats from biodata and will store this info in a file. Next time, the user wants the stats the file will be read.
- [x] New method to store the coverage given by the manager in biodata into an SQLite database and to make queries directly there.

**Comment by imedina** [comment]
Completed in new RC3
