### ISSUE TITLE
pyCGA - misleading error message when catalog is down

### ISSUE THREAD

**Issue by ernocampo** [opencb/opencga#438]
This error trace was generated, but actually catalog was down (server irresponsive). A more accurate error message should be displayed.
```
  File "/usr/local/lib/python2.7/dist-packages/pyCGA/CatalogWS.py", line 174, in link
    calculateChecksum=str(calculateChecksum).lower(), **options)
  File "/usr/local/lib/python2.7/dist-packages/pyCGA/RestExecutor.py", line 260, in general_method
    for batch in self.run_ws(url, skip=skip, limit=limit, step=pag):
  File "/usr/local/lib/python2.7/dist-packages/pyCGA/RestExecutor.py", line 158, in run_ws
    error = r['error']
KeyError: 'error'
```
Also, these lines where in catalog logs, which suggest there might be a leak going on:
```
SEVERE: 
java.lang.OutOfMemoryError: Java heap space
```
Although logs after that also showed some apparently successful operations.

**Comment by ernesto-ocampo** [comment]
From the code, I can tell that this wouldn't have happened if the server had been unreachable - it might have been that the server still responded _something_ (that did not have the 'error' key), while the actual catalog application was not responding. That would explain the fact that some apparently successful messages appeared in catalog logs after having reported the out of memory error.

**Comment by dapregi** [comment]
There is a new PyCGA client since 02/02/2017 where this error message is no longer a problem.
I would advise to close this issue.
