### ISSUE TITLE
Batch operations failure handling in catalog

### ISSUE THREAD

**Issue by mh11** [opencb/opencga#447]
Large number of files are processed in batches. When something goes wrong, the file status does not reflect the actual progress made of loading / merging.

e.g 
We load / merge 100 files in batches of 10. In the 3 batch merge (files 30-40) an error occurs. In catalog all 100 files are labeled the same (back to transformed). 
Restarting the load/merge fails, because the backend DB throws an exception while trying to merge there first batch (again).

**Comment by j-coll** [comment]
Some more work still needed if the StudyConfiguration is not correct (i.e: some operations failed without notification)

Some kind of `--resume` param for indexing.

**Comment by j-coll** [comment]
Fixed at #465
