### ISSUE TITLE
Index and annotate non human variants

### ISSUE THREAD

**Issue by apaytuvi** [opencb/opencga#454]
Is there the possibility to index and annotate VCF variants of non-human species?

I did:

```
#load and transform variants
./opencga-storage.sh index-variants -i /opt/opencga/sessions/users/andreu/projects/78/79/All_mpileup20000.vcf --study-id 78 --file-id 88
#finishing job (--> for bierapp)
./opencga.sh jobs finished --force -id 134 -u andreu -p xxxx
```

But this does not work. I can't query variants through `cellbase`. Am I using the correct command?

Thank you.

**Comment by j-coll** [comment]
Hi @apaytuvi,

Which version of OpenCGA are you using?

You should be able to index VCFs from non-human species. There are two things to keep in mind when indexing non-human species:

- Different ploidy : Which should be fully supported. 
- Different annotation : That you have to specify to get the proper annotation from cellbase.

It may happen that Cellbase does not have the required species. In that situation, you can provide custom annotation.

When creating the project in catalog, you can specify the species and assembly that you are using. In this case, the CellbaseAnnotator will ask for the proper annotation.

BTW: I don't understand the commands that you are using. You are not supposed to use opencga-storage.sh. Is that the commandline for the job 134? 

TODO:
 - [ ] Add a tutorial about how to load non-human data.
