### ISSUE TITLE
Example of whole JSON path for "include" and "exclude"

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#464]
Projection is a great way to reduce a volume of data transferred and processed across all the layers, but I had a hard time to make it work in opencga. 

**include** and **exclude** parameters are defined as:

```
include - Fields included in the response, whole JSON path must be provided
exclude - Fields excluded in the response, whole JSON path must be provided
```

Could you please give us an example what **include** and **exclude** parameters should look like (e.g. for variants endpoint `host:port/opencga-1.0.0-rc2.1/webservices/rest/v1/studies/2/variants`)

Thank you in advance.

**Comment by j-coll** [comment]
Hi @dnafault,

Not all the fields can be included/excluded from a variant object. This are the fields that can be used:

```
 - studies
 - studies.samplesData
 - studies.files
 - studies.stats
 - annotation
```

You can provide more than one field comma separated. Keep in mind that you can't use include and exclude at the same time.

- [ ] Improve include/exclude documentation in Swagger and Wiki

**Comment by dnafault** [comment]
Thanks Jacobo
