### ISSUE TITLE
webservices (swagger) over https?

### ISSUE THREAD

**Issue by sm766** [opencb/opencga#466]
Hi,

I'm trying to configure opencga over https on a public facing server. Even if I allow mixed content thus traversing the below warning:

> Mixed Content: The page at 'https://mydomain.com/opencga/webservices/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mydomain.com/opencga/webservices/rest/swagger.json'. This content should also be served over HTTPS.

I still receive an error (Chrome and Firefox on Linux):

> XMLHttpRequest cannot load http://mydomain.com/opencga/webservices/rest/swagger.json. Redirect from 'mydomain.com/opencga/webservices/rest/swagger.json' to 'https://mydomain.com/opencga/webservices/rest/swagger.json' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://funcgen.haem.cam.ac.uk' is therefore not allowed access.

If I port forward the application server's port over ssh I can load the webservices interface locally, eg:

`http://localhost:<forwarded_port>/opencga/webservices/`

So this does appera to be an https issue. This is all after a successful login through the client referencing the https port on my application server:

`./opencga.sh users login -u sm766 -p -L DEBUG`

returning:

> 2016-12-16 15:01:05 [main] DEBUG UsersCommandExecutor:201 - Loading configuration from '/usr/local/opencga/catalog/conf/client-configuration.yml'
> 2016-12-16 15:01:05 [main] DEBUG UsersCommandExecutor:241 - Loading configuration from '/usr/local/opencga/catalog/conf/catalog-configuration.yml'
> 2016-12-16 15:01:05 [main] DEBUG UsersCommandExecutor:77 - sessionFile = UserConfigFile{userId='sm766', sessionId='<obfuscated>', login=2016-12-16T14:56:20.385, logout=null, timestamp=1481900180421}
> 2016-12-16 15:01:05 [main] DEBUG UsersCommandExecutor:56 - Executing users command line
> 2016-12-16 15:01:05 [main] DEBUG UsersCommandExecutor:194 - Login
> 2016-12-16 15:01:06 [main] DEBUG UserClient:236 - POST URL: https://mydomain.com:8443/opencga/webservices/rest/v1/users/sm766/login?sid=HoHkyPmpQ5v2ZergtGny&skip=0&limit=2000
> 2016-12-16 15:01:06 [main] DEBUG UserClient:210 - GET URL: https://mydomain.com:8443/opencga/webservices/rest/v1/users/sm766/logout?sid=HoHkyPmpQ5v2ZergtGny&skip=0&limit=2000
> You have been logged correctly. This is your new session id <obfuscated>

Any help to get this all setup over https would be appreciated.

Thanks

**Comment by imedina** [comment]
Thanks for the feedback, and sorry for not getting back sooner. This has been addressed in version 1.1.0, released last week.
