### ISSUE TITLE
"./opencga.sh users login" takes too much time

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#469]
It takes 23 min to get results from "./opencga.sh users login --user *** --password" with rc2.1. There is no such delay with rc1.

**Comment by pfurio** [comment]
Hi, that is quite weird. We haven't seen that issue so far.

Can you make that same query writing "--log-level debug" at the end as well as writing the part regarding to your query from the catalina.out file in Tomcat.

Thanks in advance!

**Comment by dnafault** [comment]
There is no delay with 1.0.0-rc3.
