### ISSUE TITLE
Changes in the configuration and maven properties

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#480]
Due to the latest changes made in #476, some of the property names as well as some of the parameters present in the **configuration.yml** file are not properly named. The changes to be done are:

_Configuration.yml_

- Rename **emailServer** for **email**. Email property contains the host, port... so it is clear that is the email server.
- Rename **database** for **catalog**. That database information only makes sense within catalog and since this configuration is the most general one for opencga (containing catalog), we should make that more clear.
- Group the **rest** and **grpc** parameters within a one called **server** since they both make reference to the webservices.

_Properties_ (pom.xml)

- Remove deprecated properties such as **OPENCGA.CATALOG.DB.DATABASE**. This is now replaced by the OPENCGA.DB.PREFIX property.
- Remove word **CATALOG** from several properties such as OPENCGA.DB.PREFIX, *.ROOTDIR and *.JOBS.ROOTDIR since it is a general configuration.
- ...

In general, make the property names match up with the parameters defined in the general configuration file.

**Comment by imedina** [comment]
In particular the Maven properties changes are:

1. Remove CATALOG from:

> OPENCGA.**CATALOG**.DB.PREFIX
> OPENCGA.**CATALOG**.ROOTDIR
> OPENCGA.**CATALOG**.JOBS.ROOTDIR
> 
> OPENCGA.**CATALOG**.ORGANISM.SCIENTIFIC_NAME
> OPENCGA.**CATALOG**.ORGANISM.COMMON_NAME
> OPENCGA.**CATALOG**.ORGANISM.TAXONOMY_CODE
> OPENCGA.**CATALOG**.ORGANISM.ASSEMBLY

2. Rename:
 * OPENCGA.ANALYSIS.EXECUTION.MANAGE to OPENCGA.EXECUTION.MODE
 * OPENCGA.CATALOG.DAEMON.PORT to OPENCGA.MONITOR.PORT

**Comment by j-coll** [comment]
In reference with this issue #468 I would add 2 more properties to the maven:
```
OPENCGA.CATALOG.DB.CONNECTIONSPERHOST
OPENCGA.STORAGE.MONGO.CONNECTIONSPERHOST
```

Which will define the option "connectionsPerHost" to connect to MongoDB. Default value should be 20 in both cases

**Comment by imedina** [comment]
I think the do not follow the policy name, maybe they should be:
OPENCGA.CATALOG.DB.**CONNECTIONS_PER_HOST**

and:
OPENCGA.STORAGE.MONGO**DB**.**CONNECTIONS_PER_HOST**

**Comment by j-coll** [comment]
I have modified some variables from opencga-storage to match with the naming conventions.

| New name                                                      |Old name                                                     |
|---------------------------------------------------------------|-------------------------------------------------------------|
| `OPENCGA.STORAGE.DEFAULT_ENGINE                              `| `OPENCGA.STORAGE.ENGINE.DEFAULT                            `|
| `OPENCGA.STORAGE.CACHE.HOST                                  `|                                                             |
| `OPECNGA.STORAGE.SEARCH.HOST                                 `|                                                             |
| `OPENCGA.STORAGE.STUDY_METADATA_MANAGER                      `| `OPENCGA.STORAGE.STUDY.METADATA.MANAGER                    `|
| `OPENCGA.STORAGE.MONGODB.VARIANT.DB.AUTHENTICATION_DATABASE  `| `OPENCGA.STORAGE.MONGODB.VARIANT.DB.AUTHENTICATION_DATABASE`|
| `OPENCGA.STORAGE.MONGODB.VARIANT.DB.CONNECTIONS_PER_HOST     `|                                                             |
| `OPENCGA.STORAGE.HADOOP.VARIANT.HBASE.NAMESPACE              `| `OPENCGA.STORAGE.HADOOP.HBASE.NAMESPACE                    `|
| `OPENCGA.STORAGE.HADOOP.VARIANT.ARCHIVE.TABLE.PREFIX         `| `OPENCGA.STORAGE.HADOOP.HBASE.ARCHIVE.TABLE.PREFIX         `|

And this is the final list of maven properties for configuring opencga-storage:

__Storage__
`OPENCGA.STORAGE.DEFAULT_ENGINE`
`OPENCGA.STORAGE.CACHE.HOST`
`OPECNGA.STORAGE.SEARCH.HOST`
`OPENCGA.STORAGE.STUDY_METADATA_MANAGER`

__Storage Variants general__
`OPENCGA.STORAGE.VARIANT.DB.HOSTS`
`OPENCGA.STORAGE.VARIANT.DB.USER`
`OPENCGA.STORAGE.VARIANT.DB.PASSWORD`

__Storage Alignments general__
`OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS`
`OPENCGA.STORAGE.ALIGNMENT.DB.USER`
`OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD`

__Storage-mongodb__
`OPENCGA.STORAGE.MONGODB.VARIANT.DB.AUTHENTICATION_DATABASE`
`OPENCGA.STORAGE.MONGODB.VARIANT.DB.CONNECTIONS_PER_HOST`

__Storage-hadoop__
`OPENCGA.STORAGE.HADOOP.VARIANT.DB.HOSTS`
`OPENCGA.STORAGE.HADOOP.VARIANT.DB.USER`
`OPENCGA.STORAGE.HADOOP.VARIANT.DB.PASSWORD`
`OPENCGA.STORAGE.HADOOP.VARIANT.HBASE.NAMESPACE`
`OPENCGA.STORAGE.HADOOP.VARIANT.ARCHIVE.TABLE.PREFIX`

**Comment by pfurio** [comment]
- Modified OPENCGA.CLIENT.HOST  for OPENCGA.CLIENT.REST.HOST
- Added OPENCGA.CLIENT.GRPC.HOST
