### ISSUE TITLE
404 error on opencha.sh after 555be12 commit

### ISSUE THREAD

**Issue by danielnavarrogomez** [opencb/opencga#483]
Hi,

After this the commit [555be12](https://github.com/opencb/opencga/commit/555be123252c0b883055a4eb24b66784d12eb307) and changing my m2 config to:
`
            <OPENCGA.CLIENT.REST.HOST>http://localhost:8080/${opencga.war.name}</OPENCGA.CLIENT.REST.HOST>
            <OPENCGA.CLIENT.GRPC.HOST>http://localhost:9091</OPENCGA.CLIENT.GRPC.HOST>
            <OPENCGA.CLIENT.ORGANISM.SCIENTIFIC_NAME>Homo sapiens</OPENCGA.CLIENT.ORGANISM.SCIENTIFIC_NAME>
            <OPENCGA.CLIENT.ORGANISM.COMMON_NAME>human</OPENCGA.CLIENT.ORGANISM.COMMON_NAME>
            <OPENCGA.CLIENT.ORGANISM.TAXONOMY_CODE>9606</OPENCGA.CLIENT.ORGANISM.TAXONOMY_CODE>
            <OPENCGA.CLIENT.ORGANISM.ASSEMBLY>GRCh37</OPENCGA.CLIENT.ORGANISM.ASSEMBLY>
`

opencga.sh is getting my a 404 error but opencga-analysis.sh is working fine.

**Comment by pfurio** [comment]
Hi Daniel,

Just checkout that commit, compile and run a few commands with opencga.sh and everything seems to be working fine. Are you sure you have changed the properties properly? That commit was just a rename of the property names but nothing else.

**Comment by danielnavarrogomez** [comment]
Hi, 

I just did a pull this morning, recompiled again and it is solved.
