### ISSUE TITLE
variant query text format issue

### ISSUE THREAD

**Issue by mh11** [opencb/opencga#484]
The command 
`opencga.sh variant query --count --region 2 --studies XXX`
produces the following error message:
`Error: Long not yet supported in text format`

With YAML, it works fine.

**Comment by pfurio** [comment]
This was fixed in commit e87c24f1f837a67fe5be2d064a1f1c1665fcb600. 

By default, when there is not text printer implemented for one specific object, it will be printed in YAML format.
