### ISSUE TITLE
OPENCGA.ORGANISM.SCIENTIFIC_NAME

### ISSUE THREAD

**Issue by danielnavarrogomez** [opencb/opencga#488]
Hello,

I just found that there is still some code using the former option "OPENCGA.ORGANISM.SCIENTIFIC_NAME" instead of the new one "OPENCGA.CLIENT.ORGANISM.SCIENTIFIC_NAME", the file in question is:

opencga/opencga-storage/opencga-storage-core/src/main/resources/storage-configuration.yml

https://github.com/opencb/opencga/blob/d81833d95d2e160e6256d90797e7fd71eaa42b34/opencga-storage/opencga-storage-core/src/main/resources/storage-configuration.yml

**Comment by pfurio** [comment]
Many thanks for that. We hadn't noticed. Will change it immediately.
