### ISSUE TITLE
Filters with "not" and --returned-samples thoughts  

### ISSUE THREAD

**Issue by danielnavarrogomez** [opencb/opencga#489]
Hi,

I would like to have a feature of excluding some calls using (as example) the genotype: "give me all variants that genotype is not 0/0 or ./.". Right now we are using "give me 0/1 and 1/1" but it will be more complex when you have more than one alternative for a given position.

Something that will be really interesting for us is that when you use "--returned-samples" option, only variants present on that set of samples will be returned.

Our studies are really big (hundreds of samples), but we need to analyze samples one by one instead of all together.

**Comment by j-coll** [comment]
Now you can use either negated genotypes or the filter "--sample" for this. See #543
