### ISSUE TITLE
VariantVcfMongoDataWriter

### ISSUE THREAD

**Issue by aaleman** [opencb/opencga#5]
Create a new VariantVcfMongoDataWriter.

The VariantVcfMongoDataWriter inserts all the data into MongoDB.

**Comment by j-coll** [comment]
The class [*VariantMongoDBWriter*](https://github.com/opencb/opencga/blob/develop/opencga-storage/opencga-storage-mongodb/src/main/java/org/opencb/opencga/storage/mongodb/variant/VariantMongoDBWriter.java) exists and is fully tested.
