### ISSUE TITLE
mvn build dependency issue due to unresolved cellbase version

### ISSUE THREAD

**Issue by mitochon** [opencb/opencga#50]
The current 'master' branch has dependency on  
````
<cellbase.version>3.1.0-rc</cellbase.version>
````

 * [maven central](http://mvnrepository.com/artifact/org.opencb.cellbase) shows version 3.1.0 as latest available build.
 * [latest cellbase repo](https://github.com/opencb/cellbase/blob/develop/pom.xml) shows version 3.1-SNAPSHOT as the current version

Having problems building the project / 'master' branch due to this unresolved dependency.

**Comment by imedina** [comment]
This has been fixed, now 'master/ depends on cellbase 3.1.0
