### ISSUE TITLE
(Incompatible) API changes

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#508]
It would be nice to put somewhere (Release Notes) a list of all REST API changes that come with a new release - especially, those that break compatibility.

Lack of it makes testing and migration much harder.

Particularly, list for v1.0.0-rc3's _incompatible_ changes would be really useful.

Thanks.

**Comment by imedina** [comment]
You are right, sorry very much for any inconvenience. This was something that we were going to do for sure after first stable version 1.0.0, but certainly we could have started in the RCs. I will document this here:

http://docs.opencb.org/display/opencga/Release+Notes

**Comment by dnafault** [comment]
So, since there are rc2 deployments in production already, it would be nice to see at least incompatible API changes made in rc3. Changes between 1.0.0 and rc3 won't help much for migration from rc2.
