### ISSUE TITLE
Add Search functionality with Apache Solr to Storage Engine framework

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#521]
This a long time planned feature. Currently two storage engines to index data exist: MongoDB and Apache HBase. These are great for storing and indexing huge amount of data while still providing a very good performance for most of the queries. However, there are still some important and complex queries that can take too much time in these engines, and also, there is a big interest supporting _faceted_ queries.

Adding Apache Solr to the framework - not as a storage engine - has been planned for some time. This would be a new feature of the framework and MongoDB or HBase (and any feature implementation) can use the new SearchManager as they need, notice that altohugh Solr is used for now the implementation will supoprt to add new Search engines easily. Apache Solr is not intended to store the whole data, just most the fields that are used for querying data. This will have a big impact in performance. Tasks:

- [x] Define data model for Search
- [x] Implement SearchManager, SearchDBAdaptor and SolrSearchDBAdaptor
- [x] Implement SearchIterator and SolrSearchIterator

**Comment by j-coll** [comment]
I don't know if this may affect you, if you are using underscore for composing the variantId: #528

**Comment by imedina** [comment]
This can be easily controlled, thanks!
