### ISSUE TITLE
Unable to set ACL for a group in study

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#523]
Version 1.0.0-rc3

Using command-line

1. Create study called 'SVID'
2. Create user 'philipwu'
3. Create group 'AGHA' in study: 
`
./opencga.sh studies groups-create --group AGHA --users philipwu -s SVID`

4. Set group ACL for study

`[root@localhost bin]# ./opencga.sh studies acl-create --members @AGHA -s SVID --template view_only
Could not read file AGHA: **java.io.FileNotFoundException: AGHA (No such file or directory)**
`

**Comment by pfurio** [comment]
Dear Philip, thanks for the ticket. The problem was caused when parsing the commands. This has been solved upgrading our JCommander dependency and disabling that unexpected behaviour.
