### ISSUE TITLE
member '*' doesn't enable access

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#524]
Version: 1.0.0-rc3

In the command-line documentation, it mentions that '*' can be added as an ACL member to a study.
I've also set the permissions for '*'.

But I still can't other users to get access to the study. I believe i'm doing everything correctly, so I suspect there might be a bug here.

**Comment by pfurio** [comment]
There was an issue not only with * but also with anonymous user. You can see the ticket #501. This was solved in the current 1.0.0-final. Right now we are just bug fixing so it is safe moving to that version.

Best regards.
