### ISSUE TITLE
Building opencga error: 'opencga-storage-hadoop-core' failure

### ISSUE THREAD

**Issue by ljq12697** [opencb/opencga#527]
Here is the error log:

Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/opencb/opencga/opencga-storage-hadoop-deps/1.0.0-rc3-SNAPSHOT/opencga-storage-hadoop-deps-1.0.0-rc3-SNAPSHOT-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] opencga ............................................ SUCCESS [ 25.677 s]
[INFO] opencga-core ....................................... SUCCESS [07:30 min]
[INFO] opencga-catalog .................................... SUCCESS [02:54 min]
[INFO] opencga-storage .................................... SUCCESS [  9.109 s]
[INFO] opencga-storage-core ............................... SUCCESS [04:54 min]
[INFO] opencga-storage-server ............................. SUCCESS [ 26.383 s]
[INFO] opencga-storage-mongodb ............................ SUCCESS [  9.211 s]
[INFO] opencga-storage-app ................................ SUCCESS [ 26.721 s]
[INFO] opencga-analysis ................................... SUCCESS [ 11.364 s]
[INFO] opencga-server ..................................... SUCCESS [ 42.825 s]
[INFO] opencga-client ..................................... SUCCESS [  0.974 s]
[INFO] opencga-app ........................................ SUCCESS [ 38.113 s]
[INFO] opencga-storage-hadoop ............................. SUCCESS [  0.416 s]
[INFO] opencga-storage-hadoop-core ........................ FAILURE [08:17 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28:36 min
[INFO] Finished at: 2017-02-20T15:08:38+08:00
[INFO] Final Memory: 114M/274M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project opencga-storage-hadoop-core: Could not resolve dependencies for project org.opencb.opencga:opencga-storage-hadoop-core:jar:1.0.0-rc3: Could not find artifact org.opencb.opencga:opencga-storage-hadoop-deps:jar:tests:1.0.0-rc3-SNAPSHOT in hortonworks-releases (http://repo.hortonworks.com/content/repositories/releases/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :opencga-storage-hadoop-core

This website (https://oss.sonatype.org/content/repositories/snapshots/org/opencb/opencga/opencga-storage-hadoop-deps/1.0.0-rc3-SNAPSHOT/) cannot open now, so this process got an error.

How can I solve this problem? I downloaded the latest stable release of opencga at master branch.

**Comment by dnafault** [comment]
@imedina @j-coll

Can you please restore 1.0.0-rc3-SNAPSHOT in [*] as its deletion breaks stable release-1.0.0-rc3 build from master.  

[*] https://oss.sonatype.org/content/repositories/snapshots/org/opencb/opencga/opencga-storage-hadoop-deps/

**Comment by j-coll** [comment]
This problem it's being fixed in version 1.0.0

Sorry for the problems.
