### ISSUE TITLE
Emails as usernames used in Mongo database name are not supported

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#532]
Version release-1.0.0-final

I'd like to use email addresses as usernames in opencga.
However, the problem is that mongodb doesn't like periods being used in database names.
And I believe that usernames are embedded in the mongo database names.

How can we address this? Is there a simple way for me to modify the code to essentially replace periods with underscores perhaps?

thanks

**Comment by Philip-Wu** [comment]
I found a way to hack the code to get it working, although i'm not sure if this is the best way to do it.

In the **StorageOperation.getDataStoreByProjectId()** method there is a line of code that reads:

`String dbName = prefix + userId + '_' + alias;`

Change it to:

`String dbName = prefix + userId.replaceAll("\\.", "-") + '_' + alias;`

Effectively replacing the periods with a dash. Mongodb is happy now.

**Comment by j-coll** [comment]
That's a really good place to fix that.

This is a problem that MongoDB and Apache Phoenix will share, and I can imagine that many other possible databases.

But being this something to do with the StorageEngine implementation, probably it should be at the StorageEngine level. I will discuss this with @imedina
