### ISSUE TITLE
studies shared with *, not showing up in user projects

### ISSUE THREAD

**Issue by Philip-Wu** [opencb/opencga#534]
Version 1.0.0-final

Say i have a study and I've set the ACL membership to asterik: *

When calling the web service /users/{user}/projects, the projects that have ACL membership with *, don't show up in the list.

This is regardless, if I set the 'shared' parameter to true or false.

I can confirm that access to the project work, if I query based on the projectId. But this assumes I already know the projectId. How will users know the projectId if they can't even see those projects?

**Comment by pfurio** [comment]
A new webservice projects/search was added for release 1.2.0 (#651). This kind of queries are now much more easy to do
