### ISSUE TITLE
New variants SAMPLES filter

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#543]
Variants where ALL samples are present (not missing or reference. With the main alternate)

At some point, this filter should accept ALL or ANY sample. Initially will support only ALL samples.

To speed up queries, internally, the filter should get the indexed files where these samples are present and add the param FILES if absent.

These samples should be used as `RETURNED_SAMPLES` is missing.

Example:

|      |S1   | S2  | S3  |
|------|-----|-----|-----|
|VAR_1 | 0/0 |**0/1**| 1/1 |
|VAR_2 |**0/1**|**0/1**| 1/1 |
|VAR_3 |**0/1**| 0/0 | 0/1 |
|VAR_4 | 0/0 | 0/0 | 0/0 |
|VAR_5 | 0/0 |**0/1**| 1/1 |

With sample S1
 - input: [S1], output : [VAR_2, VAR_3]

With sample S1 AND S2
 - input: [S1,S2], output : [VAR_2]

 - [x] Implemented in MongoDB
 - [x] Implemented in HBase-Phoenix
 - [x] Add parameter to REST and CLI

**Comment by imedina** [comment]
This looks good to me. Just to remind that the parameter should be called sample, we use singular no plurals names (e.g. --gene). As mentioned this could be implemented together with --sample-filter
