### ISSUE TITLE
Enhance Variables to support Integer/Float 

### ISSUE THREAD

**Issue by wbari** [opencb/opencga#545]
Currently Variables inside VariableSet and AnnotationSet support the following data types: 
CATEGORICAL, NUMERIC, OBJECT, BOOLEAN, TEXT. Integer, float, double, long all are supported under NUMERIC category and doesn't respect datatype on persistence. User would like to distinguish among these data types, store data with proper type and later retrieve it as well. 

For example : INTEGER 1 must be stored as 1 and returned as 1 as well whereas Double 2.0 must be stored as double and returned as 2.0

**Comment by pfurio** [comment]
_NUMERIC_ variable type has been removed and two new variables have been added, _INTEGER_ and _DOUBLE_ as can be seen [here](https://github.com/opencb/opencga/blob/develop/opencga-catalog/src/main/java/org/opencb/opencga/catalog/models/Variable.java#L83).

- [ ] A migration script will be needed to change existing _NUMERIC_ variable types for _DOUBLE_

**Comment by pfurio** [comment]
Migration script can be found in https://gist.github.com/pfurio/ace5d31a4f42750801ac4070bd830e8b
