### ISSUE TITLE
Error in link command

### ISSUE THREAD

**Issue by agaor** [opencb/opencga#570]
Sometimes when you use the "link" command, the first time you use it on a file it gives an "Invalid alias for 'name' exception." 

I have discovered that the error occurs when the sample name of the vcf file contains a "."
./opencga.sh files link -i GTB0329.vcf -s trio7

2017-04-04 20:12:08 [main] WARN  FileMetadataReader:354 - Some samples from file "GTB0329.vcf" were not registered in Catalog. Registering new samples: [Trio_7_IonXpress_025_rawlib.bam]
org.opencb.opencga.catalog.exceptions.CatalogParameterException: Error in alias: Invalid alias for 'name'.
at org.opencb.opencga.catalog.utils.ParamUtils.checkAlias(ParamUtils.java:90)

The second time you launch the same command on the same file, no error occurs and shows that you have made the link correctly but it is not true.

./opencga.sh files link -i ../examples/files/nekane/trio7/GTB0329.vcf -s trio7
#NAME	TYPE	FORMAT	BIOFORMAT	DESCRIPTION	CATALOG_PATH	FILE_SYSTEM_URI	ID	STATUS	SIZE	INDEX_STATUS	RELATED_FILES	SAMPLES
GTB0329.vcf	FILE	UNKNOWN	NONE	null	GTB0329.vcf	file:///opt/opencga/GTB0329.vcf	42	READY	-1	NONE

When you try to index this file it tells you that it has nothing to do.

I have discovered that the error occurs when the sample name of the vcf file contains a ".". 

@pfurio

**Comment by pfurio** [comment]
This problem occurs when we automatically attempt to create the samples present in the VCF file. A valid sample name should contain letters, numbers or any of the symbols "_", "-". However, the "." symbol was not considered valid.

The "." symbol is going to will be accepted from now on to avoid this kind of situations.
