### ISSUE TITLE
Variant filtering in a samples group

### ISSUE THREAD

**Issue by dnafault** [opencb/opencga#578]
It seems not being possible to find variants that exist in some of the samples in a given group of samples, as 'samples' and 'genotype' (in /{version}/analysis/variant/query) treat variants as a logical conjunction across all samples. This makes impossible to implement "virtual cohorts" (sub-sets of whole cohorts, based on list of samples selected by some criteria), which would have a lot of useful use cases.

I wonder if there is a way to do this kind of selection inside a given group of samples IDs.

**Comment by j-coll** [comment]
Hi @dnafault ,

Usually we allow in many filters to separate values with comma (AND) and semicolon (OR), but not for this filter. Currently is not possible to filter that way.

One possibility is to use the `FILES` filter, but this only will work if the virtual cohort can be represented with a set of files (e.g. if the VCFs were single sample). Also, this filter is only available for mongodb.

**Comment by dnafault** [comment]
Thanks Jacobo. We use per-sample g.vcf files to load to hbase, but joint-called vcfs for mongo, as with current opencga data model it's terribly inefficient to load more than a hundred separate vcfs to mongo. Unfortunately, selection by files is not an option for us.

**Comment by j-coll** [comment]
Take a look to this ticket that you may find interesting for the next release: https://github.com/opencb/opencga/issues/574 .
Enabling this option, we expect have a big speed-up when loading single sample vcfs in MongoDB. I am still running some performance tests.

Anyway, I will try to schedule the OR for that filter.

**Comment by dnafault** [comment]
Having thousands of samples, we've gotta move to hbase. OR would be infinitely helpful.

**Comment by dnafault** [comment]
Is OR implemented by any chance ?

**Comment by j-coll** [comment]
OR is now implemented in both SAMPLE and GENOTYPE filters.
