### ISSUE TITLE
VariantQueryParam INCLUDE_FORMATS. Select format fields to return

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#608]
Currently, we can include or exclude some samples from a variant. This will result on returning all the information available for those samples (all the fields from the FORMAT). But the user may need only some of them. A new QueryParam would be needed to select the required format fields.

``` java
QueryParam INCLUDE_FORMAT("include-format")
```

1. This field should accept a list of formats to return. 
2. The order will be irrelevant. 
3. If one variant does not have all the required formats, the variant can skip that field.
3. Shortcuts "`all`" and "`none`" must be accepted.
3. If the param is not specified, all formats will be returned (current behaviour)
3. An extra param "--include-genotypes" will add GT to the included formats.

 - [x] Accept param at opencga-storage-mongodb. Related: #221
 - [x] Accept param at opencga-storage-hadoop. Related: #602
 - [x] Add to the Command line and REST server
   - [x] Add param --include-genotypes as shoutcut

**Comment by imedina** [comment]
CLI parameters should be in singular:  --include-genotype and  --include-format

**Comment by j-coll** [comment]
I have found an "interesting" mongodb behaviour
```javascript
> db.variants.find({}, {studies:{$elemMatch:{sid:1}}, "studies.files":1})
{  studies : [ { sid : 1, files : [ ... ] } ]  }

> db.variants.find({}, {"studies.files":1, studies:{$elemMatch:{sid:1}}})
{  studies : [ { sid : 1, files : [ ... ] , gt : { ... } } ]  }
```
