### ISSUE TITLE
Accept more aggregated files

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#61]
Aggregated files are a complicated problem, due to the number of different ways that the aggregated data can be represented. A generic way to parse this data have to be implemented, in order to understand aggregated files.

**Comment by jmmut** [comment]
resolved in https://github.com/opencb/opencga/pull/46 and https://github.com/opencb/opencga/pull/49,

using the development made in biodata: https://github.com/opencb/biodata/pull/34, https://github.com/opencb/biodata/pull/35 and https://github.com/opencb/biodata/pull/36
