### ISSUE TITLE
Implement JWT for OpenCGA

### ISSUE THREAD

**Issue by wbari** [opencb/opencga#618]
Replace the existing session management mechanism with the standard JWT implementation. The new changes must be compatible with existing "sid" parameter. 

- [x] Implement JWT Session Manager 
- [x] Add Authentication in Configuration file 
- [x] Add option to CLI to add secretKey to metadata during insatllation and update later
- [x] Add option to CLI to add algorithm to metadata during insatllation and update later
- [x] Execute Unit tests and fix broken ones
- [x] Execute Fitnesse regression tests

**Comment by pfurio** [comment]
- [ ] Add a migration script for these changes. (Remove array of sessions from users and metadata collections)

**Comment by pfurio** [comment]
The migration script can be found at [script.js](https://gist.github.com/pfurio/2ca0cb2da46eac9e309101066f8758f5#file-2_jwt_migration-js)
