### ISSUE TITLE
Modify AffectationStatus in Individual

### ISSUE THREAD

**Issue by jpflorido** [opencb/opencga#620]
Individual model has these values for AffectationStatus attribute: HEALTHY_CONTROL, AFFECTED, UNAFFECTED, UNKNOWN. Maybe, it would be more suitable talk about CONTROL instead of HEALTHY_CONTROL: it is a very strong assumption to be healthy.

**Comment by pfurio** [comment]
Thanks for the ticket. We agree that the assumption is quite strong so we will be changing that like you said.

**Comment by pfurio** [comment]
This is related to #615
