### ISSUE TITLE
More flexibility when adding samples to study

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#64]
If a PED file is loaded after the associated VCF file, the samples are already stored in catalog and thus rejected with a message like:

> [main] ERROR org.opencb.opencga.app.cli.main.OpenCGAMain - Sample { name: 'NA12347'} already exists.

These existing samples should be detected and updated using the information from the PED file.

**Comment by cyenyxe** [comment]
Maybe I haven't understood the code in the commit but, doesn't it just discard the information from the pedigree file if the sample already exists? If that is the case, then the samples are detected, but not updated as the ticket asked for.

**Comment by j-coll** [comment]
The load process have 3 steps:

 1. [Create a "VariableSet" by reading the PED file, or providing one](https://github.com/opencb/opencga/blob/223acce51f598cf56b0e768a1a4412c66630631a/opencga-catalog/src/main/java/org/opencb/opencga/catalog/CatalogSampleAnnotationsLoader.java#L59)
 1. [Create all the required samples with only the name information](https://github.com/opencb/opencga/blob/223acce51f598cf56b0e768a1a4412c66630631a/opencga-catalog/src/main/java/org/opencb/opencga/catalog/CatalogSampleAnnotationsLoader.java#L97)
 1. [Annotate samples](https://github.com/opencb/opencga/blob/223acce51f598cf56b0e768a1a4412c66630631a/opencga-catalog/src/main/java/org/opencb/opencga/catalog/CatalogSampleAnnotationsLoader.java#L120)

So, in the second step (the modified by the commit), the only information added to Catalog is the name of the sample. The rest of information is added in the step 3.

**Comment by cyenyxe** [comment]
Need to backport changes to 0.5.2.
