### ISSUE TITLE
Improve FILTER query param

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#723]
In VCF, the FILTER column can contain more than one value separated by `;`. This value is stored as is in either mongo and hbase. When filtering by FILTER, if the query value contains a `;`, the parser will translate as an `AND` separator.

This will make impossible get any result where the original filter contained multiple values.

e.g.
`VAR_1  FILTER = A;B;C`
`VAR_2  FILTER = B;C`

We want to improve the behaviour of this filter:
  Query FILTER=A;B  -> `where FILTER contains 'A' AND FILTER contains 'B'`  -> VAR_1
  Query FILTER=A,B  -> `where FILTER contains 'A' OR FILTER contains 'B'`  -> VAR_1, VAR_2
  Query FILTER="A;B"  -> `where FILTER = 'A;B' ` -> none results
  Query FILTER="A;B;C"  -> `where FILTER = 'A;B;C'`  -> VAR_1
  Query FILTER="A;B;C","B;C"  -> `where FILTER = 'A;B;C' OR FILTER = 'B;C'`  -> VAR_1, VAR_1

We must accept quotes in the value of the param to specify that the semi colon is not a separator.

**Comment by imedina** [comment]
These improvements will benefit from the new index being created in #764
