### ISSUE TITLE
Indicate if "numTotalResults" is an approximated count in VariantQueryResult

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#749]
An approximated count was added in #638 as part of the integration with Solr. This will return an approximation count with about 1% of error, we need to inform users if the _numTotalResults_ returned is exact or an approximation.

This _approximateCount_ will be executed if the VariantStorageEngine intersects results from Solr and MongoDB and the param "approximateCount" is true.
It may happen that, even if the param "approxCount" is present, the result is not approximated (the number of samples was bigger than the totalCount, or the query went entirely to Solr. For this situations, it will be interesting to have a boolean field in VariantQueryResult indicating this.

- [ ] Add boolean field to specify if the total count (if any) is approximated or not

**Comment by imedina** [comment]
With this the Variant query result returned will look like this:

  {
    id: "",
    dbTime: 13,
    numResults: 10,
    _**numTotalResults**_: 5643,
    _**approximateCount**_: true,
    warningMsg: "Data from Solr + mongodb",
    errorMsg: "",
    resultType: "org.opencb.biodata.models.variant.Variant",
    result: [...]
  }

where the **5643** of _numTotalResults_ is an aproximation with ~1% error.
