### ISSUE TITLE
Rename some Variant REST query parameters

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#751]
Some Variant query parameters are inconsistent or confusing. Te aim of this ticket is to rename them maintaining backward compatibility to give users enough time to adapt to new names. These changes are:

- _ids_ to _id_
- replace prefix _returned_ of _returnedStudies_, _returnedSamples_ and _returnedFiles_ with _include_, e.g. _returnedSamples_ will be _includeSamples_
- camelcase is favoured, _include-format_ and _include-genotype_ to _includeFormat_ and to _includeGenotype_
- more camelcase for _reference_frequency_ and _alternate_frequency_
- remove _annot-_ prefix in _annot-ct_, _annot-xref_, _annot-biotype_, _annot-go_, _annot-population-maf_, ...
- CADD should be named, replace _annot-functional-score_ with _cadd_
- _sampleFilter_ to _sampleAnnotation_

As a general rule fields from the data model should be honoured when possible, for others singular is preferred.

Summary of changes:

| Old value | New value |
| ----- | ------ |
| ids | id |
| region | --- |
| chromosome | DEPRECATED use `region` instead |
| type | --- |
| reference | --- |
| alternate | --- |
| project | --- |
| studies | study |
| returnedStudies | includeStudy |
| samples | sample |
| sampleFilter | sampleAnnotation |
| genotype | --- |
| returnedSamples | includeSample |
| samplesMetadata | sampleMetadata |
| unknownGenotype | --- |
| include-format | includeFormat |
| include-genotype | includeGenotype |
| files | file |
| filter | --- |
| returnedFiles | includeFile |
| cohorts | cohort |
| maf | --- |
| mgf | --- |
| missingAlleles | --- |
| missingGenotypes | --- |
| annotationExists | --- |
| gene | --- |
| annot-ct | ct |
| annot-xref | xref |
| annot-biotype | biotype |
| polyphen | DEPRECATED use `proteinSubstitution` instead |
| sift | DEPRECATED use `proteinSubstitution` instead |
| protein_substitution | proteinSubstitution |
| conservation | --- |
| alternate_frequency | populationFrequencyAlt |
| reference_frequency | populationFrequencyRef |
| annot-population-maf | populationFrequencyMaf |
| annot-transcription-flags | transcriptionFlag |
| annot-gene-trait-id | geneTraitId |
| annot-gene-trait-name | DEPRECATED use `trait` instead |
| clinvar | DEPRECATED use `xref` instead |
| cosmic | DEPRECATED use `xref` instead |
| traits | trait |
| annot-hpo | DEPRECATED use `geneTraitId` or `trait` instead |
| annot-go | go |
| annot-expression | expression |
| annot-protein-keywords | proteinKeyword |
| annot-drug | drug |
| annot-functional-score | functionalScore |
| annot-custom | customAnnotation |

**Comment by imedina** [comment]
We also need to rename some _advanced_ parameters:

- _aproximateCountSamplingSize_
- _useSearchIndex_, accepted values: yes, no and auto

**Comment by j-coll** [comment]
- Deprecate _polyphen_ and _sift_ params. Use proteinSubstitution instead

**Comment by melsiddieg** [comment]
Hi Guys

I  just wanted to commend the new direction of using  camelCasing instead
of the hyphen, The old names  actually resulted in a bug in the R client,
as the url would not be formed correctly, I found a workaround that
involved  quoting the hyphen containing params, but this would be the best
solution.

**Comment by imedina** [comment]
Thanks for your comment!  as explained in the ticket we will keep backward compatibility for a couple of releases. With this change I feel quite confident that the API will remain pretty stable.
