### ISSUE TITLE
Source for the 1.3.0-rc release missing .git

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#763]
After downloading v1.3.0-rc via https://github.com/opencb/opencga/archive/v1.3.0-rc.tar.gz and trying to compile, I received an error that the `.git` directory was missing.

After copying over the .git folder from a cloned opencga, I was able to compile.

You may want to include the .git folder in releases or remove this dependency

**Comment by imedina** [comment]
I think there is a confusion here. OpenCGA stable _tarballs_ are intended for distributing only the binaries no the source code, this is quite useful for people that only wants to use OpenCGA, so source code and .git folder are not included in the _tar.gz_ folder.
Users aiming to compile and build OpenCGA should just Git clone the repository.

Does this make sense?

**Comment by nicholsn** [comment]
yes this makes sense for the tarball containing the packaged binaries; however, the [Releases Tab](https://github.com/opencb/opencga/releases) also lists the source code
 
- opencga-1.3.0-rc.tar.gz
- opencgaR_1.3.0.tar.gz
- Source code (zip)
- __Source code (tar.gz)__

I downloaded this source file, configured pom.xml for my environment, and tried to compile, but received this error message:

```
mvn clean install -DskipTests
...
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project opencga-core: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
...
```

Cloning the release branch worked fine, I just thought that the source code in the release tab would be equivalent to this:

```git clone -b release-1.3.0 https://github.com/opencb/opencga.git opencga-1.3.0-rc```

No worries though, it builds fine by cloning the branch directly.

**Comment by imedina** [comment]
I see what you mean. You are right, but the problem is that I **only** upload _opencga-1.3.0-rc.tar.gz_ and _opencgaR_1.3.0.tar.gz_, the other two files are generated by GitHub automatically. I will investigate how to fix them or remove them to not confuse anyone else.
Thank you very much, this very much appreciated!

**Comment by nicholsn** [comment]
ok, thanks - feel free to close this... it was just a small thing i noticed
