### ISSUE TITLE
Deleting Jobs the have created files

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#774]
I have a job that appears to be stuck in a "PREPARED" Status. When I try to delete the job, I am presented with the message below stating that "The job created 1 files. Please, delete them first.".

How do I go about either deleting this job (and files it created) or forcing it into a RUNNING state?

```
./opencga.sh jobs delete --job 8934
Error:  not yet supported in text format
---
- id: "Delete job 8934"
  dbTime: -1
  numResults: -1
  numTotalResults: -1
  warningMsg: ""
  errorMsg: "The job created 1 files. Please, delete them first."
  resultType: ""
  result: []
```

**Comment by pfurio** [comment]
Hi Nolan,

There is not a way to delete those jobs just yet unless you get into the database directly. That's one of the things we are already working on and that will be ready for release 1.4.0. However, what you should do is start the daemons to force that job to start and try to index the variant or the alignment file you have added. You can start the daemons by running the following:
`opencga-admin.sh catalog daemon --start `
Once the job finishes the execution, the job status will be internally modified to READY or ERROR depending on the success of the execution.

**Comment by nicholsn** [comment]
@pfurio thanks, it looks like the catalog demon had gone offline. This worked and it is now running. Thanks!
