### ISSUE TITLE
Password asked with incomplete command lines

### ISSUE THREAD

**Issue by pfurio** [opencb/opencga#785]
--password parameter is no longer asked when using opencga-admin.sh command line. However, the password is asked even if the command line is incomplete or the user is asking for help with --help parameter.

We should only ask for the admin password whenever it makes sense.

**Comment by pfurio** [comment]
4c855f86242cde507d416d0d34bb9cdeab54b150 fixes the issue.

**Comment by j-coll** [comment]
@pfurio 
What about throwing an exception if the arg `--password` is already present? 
Should this apply also for "users create" and "users password"?

**Comment by pfurio** [comment]
Because this has been a recent change in this release, what we are going to do in this version is allow users write --password without raising an exception. However, if that's the case we will print a warning message saying that they should not do it and that it will be forbidden in future releases.

Regarding adding --password automatically to the other command lines, that will be probably added in a future release.
