### ISSUE TITLE
group users can not access shared study

### ISSUE THREAD

**Issue by melsiddieg** [opencb/opencga#797]
Although users can be easily added to study groups, and have the full group permissions, e.g., analyst or admin permissions, they still can not access the shared study with following error **No projects found for user**  
Indeed upon querying the user info, it does not appear that the study group users are affiliated to any project.
Interestingly, permission sharing works perfectly for the anonymous user "*", are there any extra steps required to get users access to a particular study?

**Comment by imedina** [comment]
Hi,

Thanks for reporting this, can you let us know the version or commit your are using? Thanks!

**Comment by melsiddieg** [comment]
Hi,

I am using openCGA version 1.4-dev, commit  00fd12fef82f0e77dc2d

**Comment by pfurio** [comment]
Issue should be fixed in latest 1.4.2 release. Please, reopen ticket if the issue persists.
