### ISSUE TITLE
Review and improve Variant Annotation in OpenCGA Storage

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#805]
The status of variant annotation in OpenCGA Storage (MongoDB, HBase and Solr) is really good. However, some information is missing and some other small improvements can be done.
This ticket aims to review the current status and implement the improvements needed. Not big changes are expected. One example is to add _clinicalSignificance_ to Solr to filter variants, another example is to decide if we add non-indexed annotation to Solr.

There is a separate issue for Solr improvements, see #822

**Comment by j-coll** [comment]
Missing information in MongoDB:

- hgvs
- cytobands
- consequenceType.proteinVariantAnnotation.functionalDescription
- populationFrequency.refHomGenotypeFreq
- populationFrequency.hetGenotypeFreq
- populationFrequency.altHomGenotypeFreq
- populationFRequency.refAllele
- populationFRequency.altAllele
- geneTraitAssociation.sources
- geneTraitAssociation.numberOfPubmeds
- geneTraitAssociation.score << Don't return 0 as default!
- geneTraitAssociation.hpo << Don't return if empty
- geneDrugInteraction.type
- score.description << don't return if empty

**Comment by j-coll** [comment]
What about "repeat", "minorAllele" and "minorAlleleFreq" ?

**Comment by imedina** [comment]
Let's add _repeat_ (it should be named _repeats_) and let's forget about minorAllele and minorAlleleFreq, they will be probably removed in the future.

**Comment by imedina** [comment]
Solr pending actions are being developed at #822
