### ISSUE TITLE
Documentation location 

### ISSUE THREAD

**Issue by ganeshab-edico** [opencb/opencga#818]
There is a [wiki](https://github.com/opencb/opencga/wiki) associated with the github project and then there is the [opencb documentation](http://docs.opencb.org/display/opencga/OpenCGA+Home) which includes opencga documentation.

Please indicate location of up-to-date documentation.

**Comment by imedina** [comment]
Hi,
Sorry for the confusion, we are migrating documentation from GitHub wiki to Confluence so please use the second one at http://docs.opencb.org/display/opencga/OpenCGA+Home

**Comment by ganeshab-edico** [comment]
Thank you very much for the response @imedina
