### ISSUE TITLE
More atomicity in catalog (e.g. creating studies)

### ISSUE THREAD

**Issue by jmmut** [opencb/opencga#83]
It would be nice if catalog could check that it can write in the filesystem and in the database before performing the real actions, so it can print more human-readable errors and achieve more atomicity.

This may be done in any action that changes several places in a synchronized way. For instance, creating study (a document in db.study and a folder skeleton in the filesystem)

**Comment by imedina** [comment]
This was implemented in OpenCGA 1.x, closing this old issue.
