### ISSUE TITLE
Update Login Message

### ISSUE THREAD

**Issue by nicholsn** [opencb/opencga#853]
When logging in via the opencga.sh CLI the message displayed is: "You have been logged correctly."

https://github.com/opencb/opencga/blob/83aec67a084d530b6669659f4e27ed3585cc3c32/opencga-app/src/main/java/org/opencb/opencga/app/cli/main/executors/catalog/UserCommandExecutor.java#L129

Should this be "You have been logged in correctly."?

(note: a user was prompted by the current message to ask me what the system is logging about their usage)

**Comment by pfurio** [comment]
Thanks @nicholsn
