### ISSUE TITLE
Allow storage, catalog and the authentication database to be in different hosts

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#87]
The authentication database is now forced to be in the same host as catalog: there is a property OPENCGA.CATALOG.DB.AUTHENTICATION.DB in "catalog.properties".

Having no similar property in "storage-mongodb.properties" also forces the storage databases to share host both with catalog and the authentication database.

**Comment by imedina** [comment]
Storage Engines and Catalog can be in different hosts right now, and Variant and Alignment in each Storage Engine can also live in different hosts.
It is true that authentication database must be in the same host of the corresponding database. Although in practice this is a very unlikely scenario, this will be study for next release.

**Comment by pfurio** [comment]
We now allow to authenticate from different services. This can be configured using the catalog-configuration file (https://github.com/opencb/opencga/blob/release-0.8.0/opencga-catalog/src/main/resources/catalog-configuration.yml)

An LDAP example would be as follows:
authenticationOrigins:
- id: ldap            # Any id
  type: LDAP          # At the moment, we only support LDAP
  host: ldap://localhost:9000
  options:
    usersSearch: dc=xx,dc=co,dc=uk # Base search to look for the users
    groupsSearch: ou=general,ou=groups,dc=xx,dc=co,dc=uk # Base search to look for the groups
