### ISSUE TITLE
Opencga Authentication token is expired 

### ISSUE THREAD

**Issue by Mohammedhusen** [opencb/opencga#883]
Hi Team,

While loading data into opencga we are getting below error.

org.opencb.opencga.catalog.exceptions.CatalogAuthenticationException: Authentication token is expired : 

any help much appreciated.

**Comment by pfurio** [comment]
Hi, 

can you give us more details regarding what you were doing? Which web services or command lines were you running? If it is just a matter of token expiration, you will simply need to authenticate again to get a new token and keep working.

**Comment by Mohammedhusen** [comment]
we have solved this error by updating session time in tomcat config file.
