### ISSUE TITLE
Exception displayed after variants PostLoad

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#89]
After finishing (apparently with success) loading a variants file, the following is displayed not always, but most of the times:

> [main] INFO org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager - Variants loaded!
> [main] INFO org.opencb.opencga.storage.app.cli.OpenCGAStorageMain - -- PostLoad variants -- file:/nfs/production2/eva/data/PRJEB5829/40_transformed/gonl.chr12.snps_indels.r5.vcf.gz.variants.json.snappy
> [main] ERROR org.opencb.opencga.lib.exec.Command - Exception occurred while executing Command null

**Comment by j-coll** [comment]
Fixed in v0.6-SNAPSHOT.
There is no exception there. The only error is to say that there is an error.
The "null" at the end of the log line is the alleged exception.
