### ISSUE TITLE
Can't reload file into Mongo after failure

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#90]
When the loading step for a JSON file is interrupted abruptly (for instance, by a job scheduler), it can't be loaded again and the following error is displayed:

> [main] ERROR org.opencb.opencga.app.cli.main.OpenCGAMain - Expected {status: READY} in IndexedFile 153

**Comment by jmmut** [comment]
Although this is patched, it would be nice if we can manage this at the system signals level

**Comment by cyenyxe** [comment]
Also, I suppose the status shouldn't be set as "READY" until the file is fully loaded, should it?

**Comment by j-coll** [comment]
System signals management is discussed in the issue #93.
In version 0.5.0, Catalog can't handle with intermediary indexation status. A file is "indexing" or "ready". This will be solved on version 0.6.0, adding more granularity.
