### ISSUE TITLE
Treat low quality reference calls as missing (no call)

### ISSUE THREAD

**Issue by imedina** [opencb/opencga#917]
Current implementation does not store reference calls in the second table _variants_. This allows to optimise disk space and improve performance. The assumption is that when a sample genotype is not present then it was a reference call since all the other genotypes including missing are stored.

The problem is that current variant callers are still far from being perfect and some variants having a reference call show a very low coverage or quality scores. So, in some use cases, users might need to confirm that _reference call_ was good enough.

A simple solution for this would be treat low quality **reference** calls as **missing** calls, so they would be stored in the _variant_ table in the same way than missing. By doing this users will know that not present reference calls have a good quality and there is no need to get them.

Users can configure low quality reference block in the configuration file, for instance DP<5 AND GQ<20.

**Comment by j-coll** [comment]
New configuration parameter:
`opencga.archive.non-ref.filter`

The filter is a list of key, operator, value, separated by ";". 
  - Keys: `QUAL`, `FILTER`, `FORMAT:format-key`, `INFO:info-key`
  - Ops: `>`, `<`, `>=`, `<=`, `=`
  - Value: 
        Numbers for operators `>`, `<`, `>=`, `<=`
        List of comma separated list of Strings for operator `=`
 
If a reference block does not have any of the required fields, will pass the filter, and will be treat as a missing.

Example: `QUAL<5;FILTER=LowQual,LowGQ;FORMAT:DP<10`
