### ISSUE TITLE
OpenCGA  build failure due to unmet and unstated solr dependency

### ISSUE THREAD

**Issue by melsiddieg** [opencb/opencga#919]
HI
There seems to be a problem with the recent build of opencga 1.4, as it fails to build openCGA with following build error as seen in this screenshot
![screenshot from 2018-10-07 12-16-16](https://user-images.githubusercontent.com/8942470/46580755-60214e00-ca2b-11e8-87a1-40958922dba2.png)

**Comment by pfurio** [comment]
Hi Mohammed, you need to pull and compile all the latest changes from biodata (hotfix-1.4.x branch) and java-common-libs (hotfix-3.7.x branch) before attempting the compilation of the branch release-1.4.0 as it is still under development.

**Comment by melsiddieg** [comment]
Thanks Pedro, I have switched to 1.4.x release and it compiled successfully
