### ISSUE TITLE
Investigate using Azure Batch for automating VCF file loading

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#937]
Currently OpenCGA only supports SGE batch queues manager. There is a simple interface to allow the use of several job schedulers, the goal was to define an interface with different implementations such as Slurm, Azure Batch or IBM LSF.

Main tasks involved here:

- [x] create a ARM template for deploying to Azure Batch
- [x] review OpenCGA interface and implement a new job scheduler client for Azure Batch in OpenCGA. OpenCGA Configuration must also be updated (@wbari )
- [x] improve documentation

**Comment by lawrencegripper** [comment]
@j-coll Here are some docs around how to use Batch:

Quick Python Sample: https://docs.microsoft.com/en-us/azure/batch/quick-run-python

Java Sample: https://github.com/Azure-Samples/azure-batch-samples/blob/master/Java/PoolAndResourceFile/src/main/java/PoolAndResourceFile.java

**Comment by lawrencegripper** [comment]
I've fixed up the sample code on my fork and submitted a PR here - https://github.com/Azure-Samples/azure-batch-samples/pull/258

**Comment by wbari** [comment]
Documented basic working of OpenCGA with Azure Batch Service : 
http://docs.opencb.org/display/opencga/How+to+Use+Azure+Batch+Service+For+Variant+Loading
