### ISSUE TITLE
Automatic path handling

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#94]
Path handling right now is a bit confusing for users due to two main causes:

* A slash is not appended to folder paths automatically
* Some paths require a "file:" prefix while others don't

Paths should be normalized by a module dedicated specifically to these matters. Maybe it even already exists something out there.

**Comment by j-coll** [comment]
This has been solved by using the [UriUtils](https://github.com/opencb/opencga/blob/feature/refactoring-conf/opencga-core/src/main/java/org/opencb/opencga/core/common/UriUtils.java) class.

This issue should be closed when the branch **frature/refactoring-conf** is merged into **develop**
