### ISSUE TITLE
Create ARM template for Daemon VM

### ISSUE THREAD

**Issue by marrobi** [opencb/opencga#944]
@imedina @j-coll @wbari can you provide some more details as to what this needs? 

As far as I know:

- [x] Open CGA Daemon in Docker - just needs OpenCGA and Java - no tomcat?
- [ ] Tooling - what?
- [x] Spec/sizing - what cpu/ram/disks etc?

**Comment by marrobi** [comment]
Arm templtae works are runs marrobi/opencga-daemon as a service using cloud-init and cloud-config. Needs robust first run script. WIP: https://github.com/marrobi/opencga/tree/feature/loginvm/opencga-app/app/scripts/azure/arm

**Comment by marrobi** [comment]
If need an OpenCGA prompt - 
```
docker run -it  --name=opencga-cmd -e HD_INSIGHTS_SSH_DNS=xxx-ssh.azurehdinsight.net -e HD_INSIGHTS_SSH_USER=xxx -e HD_INSIGHTS_SSH_PASS=xxx marrobi/opencga bash

```

**Comment by j-coll** [comment]
This server is not going to need Tomcat. Only Java and Opencga.

Regarding the specs, if we have Azure Batch for the computation, we won't need a big node here. 2 cores, 4GB and a small disk, just for the logs and the SO.

**Comment by marrobi** [comment]
Runs docker image without tomcat. Standard_D2s_v3 at present. So 2 core, 8GB.

**Comment by marrobi** [comment]
Ideally need to wait for #948 - share for configuration - and #952 or #951 Mongo DB - before proceeding. Could potentially use Mongo VM as temporary solution.

**Comment by martinpeck** [comment]
MongoDB blockers should be gone on this once the PR for sslEnabled has been merged (see #964)

**Comment by lawrencegripper** [comment]
File share mounting blockers should be gone now with this merged #948

**Comment by martinpeck** [comment]
@marrobi  to assign Joni

**Comment by lawrencegripper** [comment]
@jjcollinge
