### ISSUE TITLE
Investigate simplifying Avere setup by using ManagedIdentity

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#959]
The ARM template could create a Managed Identity which Avere would use in place of the existing Service Principal. 

I'm currently not sure if this is possible and would likely require some editing of the existing templates published by the Avere team here: https://github.com/Azure/Avere/tree/master/src/vfxt/src

Currently that template doesn't require a SP as it creates the VNET onto which it deploys the cluster itself in it's RG. In our case the cluster is deployed onto an existing VNET/Subnet which meant authentication errors occurred. To fix this I moved to using the SP instead of the Managed Identity.

**Comment by martinpeck** [comment]
@lawrencegripper can you please make sure the title and description reflect the task, and then we can assign elsewhere? Thanks!

**Comment by lawrencegripper** [comment]
I've updated with details and removed the label

**Comment by marrobi** [comment]
Closing this as Avere will not be part of the deployment. @lawrencegripper let me know if any issue with this.
