### ISSUE TITLE
Write list of available -D options

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#96]
A list of options prefixed by -D needs to be written in order to decide which ones will be kept and which ones will be moved to the set of "conventional" options.

**Comment by j-coll** [comment]
Dynamic parameters (`-D<key>=<value>`) are used to replace and add internal configuration options. 

This options are collected in [VariantStorageManager::Options](https://github.com/opencb/opencga/blob/develop/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/VariantStorageManager.java#L86) and [AlignmentStorageManager::Options](https://github.com/opencb/opencga/blob/develop/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/alignment/AlignmentStorageManager.java#L72). 
Find more info about the Storage-configuration file in the [wiki](https://github.com/opencb/opencga/wiki/Storage-Command-Line#storage-configuration-file)

A new general configuration file in yaml will be ready for the next release.
