### ISSUE TITLE
Remove -D options that are not related to internal aspects

### ISSUE THREAD

**Issue by cyenyxe** [opencb/opencga#97]
Options prefixed by -D are intended to be used for configuration or advanced internal purposed, but currently they are used for more common tasks too (such as specifying output file extensions or workflow steps to omit).

These common options must be moved to the set of standard options, documented in the default CLI help.

* Depends on https://github.com/opencb/opencga/issues/96

**Comment by imedina** [comment]
Some of this has been removed but other may still need to be removed, moving it to RC
