### ISSUE TITLE
Fix Daemon connection to catalog

### ISSUE THREAD

**Issue by j-coll** [opencb/opencga#976]
The daemon is connecting directly to the Catalog DBAdaptors using the MongoDBAdaptorFactory. 

There is a miss-configuration when constructing the DBAdaptorFactory.

Any case, the dbadaptors should not be used directly. All the queries should go through the CatalogManager.

**Comment by j-coll** [comment]
FYI: @martinpeck

**Comment by martinpeck** [comment]
I can confirm I'm seeing zero exceptions within the Daemon now, so I believe we can close this issue (which I'll do now). Thanks for the fix!
