### ISSUE TITLE
Cannot redeploy/upgrade Web Server VMSS

### ISSUE THREAD

**Issue by marrobi** [opencb/opencga#987]
Getting error:

  "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"MaxUnhealthyInstancePercentExceededInRollingUpgrade\",\r\n        \"message\": \"Rolling Upgrade failed after exceeding the MaxUnhealthyInstancePercent value defined in the RollingUpgradePolicy. 100%
of instances are in an unhealthy state - more than the threshold of 20%. To apply upgrades, consider increasing the MaxUnhealthyInstancePercent value.\"\r\n      }\r\n    ]\r\n  }\r\n}"

The redeploy is adding two new instances, which means that > 20% of machines are unhealthy. 

Current config uses defaults:

```
"upgradePolicy": {
 "mode": "Rolling",
 "rollingUpgradePolicy": {
 "maxBatchInstancePercent": 20,
 "maxUnhealthyInstancePercent": 20,
 "maxUnhealthyUpgradedInstancePercent": 20,
 "pauseTimeBetweenBatches": "PT0S"
 },
 "automaticOSUpgrade": false
 },
```

As deploying 2 instances, should they all be 50% to allow one instance to be upgraded at a time?

**Comment by marrobi** [comment]
Ok, changed upgrade policy to:
'''
     "upgradePolicy": {
                    "mode": "**Automatic**",
                    "maxBatchInstancePercent": 50,
                    "maxUnhealthyInstancePercent": 50,
                    "maxUnhealthyUpgradedInstancePercent": 0,
                    "pauseTimeBetweenBatches": "PT0S",
                    "automaticOSUpgradePolicy": {
                        "enableAutomaticOSUpgrade": true
                    }
                },
```

Note Automatic, rather than Rolling, now get:
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"BadRequest\",\r\n \"message\": \"Rolling Upgrade mode is not supported for this Virtual Machine Scale Set because a health probe is not applied to all instances. Apply the health probe to all instances in the virtual machine scale set prior to switching to rolling upgrade mode.\"\r\n }\r\n}"}]}
```

**Comment by lawrencegripper** [comment]
This is triggered as none of the instances are passing the loadtest probes as healthy. Until those healthchecks are responding correctly you can set the following parameters:

```json
        "tomcatDockerImage": {
            "value": "ricc/http-devnull"
        },
        "ivaDockerImage": {
            "value": "ricc/http-devnull"
        },
```

These run a server which responds with 200's on any path
