### ISSUE TITLE
Make scripts idempotent to avoid issues with redeployment

### ISSUE THREAD

**Issue by lawrencegripper** [opencb/opencga#989]
For example with Solr you will see `The container name "/opencga-zookeeper-3.4 is already in use by container "1e50fa40deb7d8b938a89f233ae730ad323a0f08af5495a87612069e5e35a56e". You have to remove (or rename) that container to be able to reuse that name.`

And with Azure Batch the pool won't be re-created so any updated config for the pool will be missed.

Todo:

- [x] Fix solr deployment script #995 
- [x] Remove workaround for Batch pool creation and use updated ARM API to create and manage the pool

**Comment by marrobi** [comment]
@lawrencegripper think should split this up - one issue per script?

**Comment by lawrencegripper** [comment]
I'm easy either way, feel like it could be done as 1 PR so keep 1 issue but not a strong feeling

**Comment by lawrencegripper** [comment]
Workaround removed for batch
